### ISSUE TITLE
Minecraft Dungeons Crashing After Studio Intro

### ISSUE THREAD

**Issue by HurricanePootis** [yuzu-emu/yuzu#10029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1393/r23529.10e0f3a4c

### Description of Issue

After the intro videos for the studios behind Minecraft Dungeons is finished, the last one being the Unreal Engine one, the game immediately crashes. This happens both on the official yuzu binaries available via the gui installer, and both on the AUR yuzu-mainline-git package. I built the latter with debugging symbols, and got the following data.

```
0x00007fffe4aa08ec in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffe4aa08ec in  () at /usr/lib/libc.so.6
#1  0x00007fffe4a51ea8 in raise () at /usr/lib/libc.so.6
#2  0x00007fffe4a3b53d in abort () at /usr/lib/libc.so.6
#3  0x00007fffe4a3c29e in  () at /usr/lib/libc.so.6
#4  0x00007fffe4aaa657 in  () at /usr/lib/libc.so.6
#5  0x00007fffe4aab144 in  () at /usr/lib/libc.so.6
#6  0x00007fffe4aab2d0 in  () at /usr/lib/libc.so.6
#7  0x00007fffe4aad7d0 in  () at /usr/lib/libc.so.6
#8  0x00007fffe4aae8ed in malloc () at /usr/lib/libc.so.6
#9  0x00007fffe4ca748d in operator new(unsigned long) (sz=5520) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/new_op.cc:50
#10 0x0000555555b1262f in std::__new_allocator<unsigned char>::allocate(unsigned long, void const*) (this=0x7f7e0effc640, __n=5520)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/new_allocator.h:137
#11 std::allocator<unsigned char>::allocate(unsigned long) (this=0x7f7e0effc640, __n=5520) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/allocator.h:188
#12 std::allocator_traits<std::allocator<unsigned char> >::allocate(std::allocator<unsigned char>&, unsigned long) (__a=..., __n=5520)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/alloc_traits.h:464
#13 std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_allocate(unsigned long) (this=0x7f7e0effc640, __n=5520)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/stl_vector.h:378
#14 std::vector<unsigned char, std::allocator<unsigned char> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned long, unsigned char const&) (this=0x7f7e0effc640, __position=<error reading variable: Cannot access memory at address 0xffffffff>, __n=5520, __x=@0x7f7e0effc5f0: 0 '\000')
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/vector.tcc:575
#15 0x0000555555b118d1 in std::vector<unsigned char, std::allocator<unsigned char> >::resize(unsigned long, unsigned char const&) (this=0x7f7e0effc640, __new_size=6, __x=@0x7f7e0effc5f0: 0 '\000')
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/stl_vector.h:1032
#16 Service::Audio::IAudioRenderer::RequestUpdate(Service::HLERequestContext&) (this=0x7f7e04067a90, ctx=...) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/audio/audren_u.cpp:124
#17 0x0000555555a24668 in Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::KServerSession&, Service::HLERequestContext&) (this=0x7f7e04067a90, session=<optimized out>, ctx=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/unique_ptr.h:191
#18 0x0000555555a1872d in Service::SessionRequestManager::CompleteSyncRequest(Kernel::KServerSession*, Service::HLERequestContext&) (this=0x7f7e0409e350, server_session=0x7ffe901155f0, context=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/hle_ipc.cpp:65
#19 0x0000555555a22835 in Service::ServerManager::CompleteSyncRequest(Service::ServerManager::RequestState&&) (this=0x7f7e04000bc0, request=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:391
#20 0x0000555555a2190c in Service::ServerManager::OnSessionEvent(Kernel::KServerSession*, std::shared_ptr<Service::SessionRequestManager>&&) (this=0x7f7e04000bc0, session=0x7ffe901155f0, manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:380
#21 Service::ServerManager::WaitAndProcessImpl() (this=0x7f7e04000bc0) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:301
#22 0x000055555596011b in Service::ServerManager::LoopProcessImpl() (this=0x7f7e04000bc0) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:189
#23 Service::ServerManager::LoopProcess() (this=0x7f7e04000bc0) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:184
#24 Kernel::KernelCore::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager> >&&) (this=<optimized out>, server_manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/kernel/kernel.cpp:1023
#25 0x0000555555b0a8c8 in Core::System::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager> >&&) (this=0x0, server_manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/core.cpp:943
#26 Service::ServerManager::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager> >&&) (server_manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:72
#27 Service::Audio::LoopProcess(Core::System&) (system=...) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/audio/audio.cpp:28
#28 0x0000555555965fb6 in std::function<void ()>::operator()() const (this=0x4be2) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:591
#29 Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1::operator()() const
    (this=0x555558e5f538) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/kernel/kernel.cpp:1084
#30 std::__invoke_impl<void, Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1>(std::__invoke_other, Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1&&)
    (__f=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:61
#31 std::__invoke<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1>(Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1&&) (__fn=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:96
#32 std::thread::_Invoker<std::tuple<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x555558e5f538) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_thread.h:258
#33 std::thread::_Invoker<std::tuple<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&--Type <RET> for more, q to quit, c to continue without paging--
)::$_1> >::operator()() (this=0x555558e5f538) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_thread.h:265
#34 std::thread::_State_impl<std::thread::_Invoker<std::tuple<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1> > >::_M_run() (this=0x555558e5f530) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_thread.h:210
#35 0x00007fffe4cd72c3 in std::execute_native_thread_routine(void*) (__p=0x555558e5f530) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:82
#36 0x00007fffe4a9ebb5 in  () at /usr/lib/libc.so.6
#37 0x00007fffe4b20d90 in  () at /usr/lib/libc.so.6

```

### Expected Behavior

The game should load into the menu; I have done it before, but it seems like there was a regression in the past week.

### Reproduction Steps

1) Download Yuzu
2) Get a copy of Minecraft Dungeons from your switch
3) Launch said copy from Yuzu
4) Crash

### Log File

```
0x00007fffe4aa08ec in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffe4aa08ec in  () at /usr/lib/libc.so.6
#1  0x00007fffe4a51ea8 in raise () at /usr/lib/libc.so.6
#2  0x00007fffe4a3b53d in abort () at /usr/lib/libc.so.6
#3  0x00007fffe4a3c29e in  () at /usr/lib/libc.so.6
#4  0x00007fffe4aaa657 in  () at /usr/lib/libc.so.6
#5  0x00007fffe4aab144 in  () at /usr/lib/libc.so.6
#6  0x00007fffe4aab2d0 in  () at /usr/lib/libc.so.6
#7  0x00007fffe4aad7d0 in  () at /usr/lib/libc.so.6
#8  0x00007fffe4aae8ed in malloc () at /usr/lib/libc.so.6
#9  0x00007fffe4ca748d in operator new(unsigned long) (sz=5520) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/new_op.cc:50
#10 0x0000555555b1262f in std::__new_allocator<unsigned char>::allocate(unsigned long, void const*) (this=0x7f7e0effc640, __n=5520)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/new_allocator.h:137
#11 std::allocator<unsigned char>::allocate(unsigned long) (this=0x7f7e0effc640, __n=5520) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/allocator.h:188
#12 std::allocator_traits<std::allocator<unsigned char> >::allocate(std::allocator<unsigned char>&, unsigned long) (__a=..., __n=5520)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/alloc_traits.h:464
#13 std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_allocate(unsigned long) (this=0x7f7e0effc640, __n=5520)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/stl_vector.h:378
#14 std::vector<unsigned char, std::allocator<unsigned char> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned long, unsigned char const&) (this=0x7f7e0effc640, __position=<error reading variable: Cannot access memory at address 0xffffffff>, __n=5520, __x=@0x7f7e0effc5f0: 0 '\000')
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/vector.tcc:575
#15 0x0000555555b118d1 in std::vector<unsigned char, std::allocator<unsigned char> >::resize(unsigned long, unsigned char const&) (this=0x7f7e0effc640, __new_size=6, __x=@0x7f7e0effc5f0: 0 '\000')
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/stl_vector.h:1032
#16 Service::Audio::IAudioRenderer::RequestUpdate(Service::HLERequestContext&) (this=0x7f7e04067a90, ctx=...) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/audio/audren_u.cpp:124
#17 0x0000555555a24668 in Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::KServerSession&, Service::HLERequestContext&) (this=0x7f7e04067a90, session=<optimized out>, ctx=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/unique_ptr.h:191
#18 0x0000555555a1872d in Service::SessionRequestManager::CompleteSyncRequest(Kernel::KServerSession*, Service::HLERequestContext&) (this=0x7f7e0409e350, server_session=0x7ffe901155f0, context=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/hle_ipc.cpp:65
#19 0x0000555555a22835 in Service::ServerManager::CompleteSyncRequest(Service::ServerManager::RequestState&&) (this=0x7f7e04000bc0, request=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:391
#20 0x0000555555a2190c in Service::ServerManager::OnSessionEvent(Kernel::KServerSession*, std::shared_ptr<Service::SessionRequestManager>&&) (this=0x7f7e04000bc0, session=0x7ffe901155f0, manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:380
#21 Service::ServerManager::WaitAndProcessImpl() (this=0x7f7e04000bc0) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:301
#22 0x000055555596011b in Service::ServerManager::LoopProcessImpl() (this=0x7f7e04000bc0) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:189
#23 Service::ServerManager::LoopProcess() (this=0x7f7e04000bc0) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:184
#24 Kernel::KernelCore::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager> >&&) (this=<optimized out>, server_manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/kernel/kernel.cpp:1023
#25 0x0000555555b0a8c8 in Core::System::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager> >&&) (this=0x0, server_manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/core.cpp:943
#26 Service::ServerManager::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager> >&&) (server_manager=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/server_manager.cpp:72
#27 Service::Audio::LoopProcess(Core::System&) (system=...) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/service/audio/audio.cpp:28
#28 0x0000555555965fb6 in std::function<void ()>::operator()() const (this=0x4be2) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_function.h:591
#29 Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1::operator()() const
    (this=0x555558e5f538) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/core/hle/kernel/kernel.cpp:1084
#30 std::__invoke_impl<void, Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1>(std::__invoke_other, Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1&&)
    (__f=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:61
#31 std::__invoke<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1>(Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1&&) (__fn=...)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/invoke.h:96
#32 std::thread::_Invoker<std::tuple<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x555558e5f538) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_thread.h:258
#33 std::thread::_Invoker<std::tuple<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&--Type <RET> for more, q to quit, c to continue without paging--
)::$_1> >::operator()() (this=0x555558e5f538) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_thread.h:265
#34 std::thread::_State_impl<std::thread::_Invoker<std::tuple<Kernel::RunHostThreadFunc(Kernel::KernelCore&, Kernel::KProcess*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::function<void ()>&&)::$_1> > >::_M_run() (this=0x555558e5f530) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/std_thread.h:210
#35 0x00007fffe4cd72c3 in std::execute_native_thread_routine(void*) (__p=0x555558e5f530) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:82
#36 0x00007fffe4a9ebb5 in  () at /usr/lib/libc.so.6
#37 0x00007fffe4b20d90 in  () at /usr/lib/libc.so.6

```

### System Configuration

CPU: Ryzen 5 5600X
GPU/Driver: AMD Radeon RX 580 With Mesa 23.0.1
RAM: 32GB DDR4
OS: Arch Linux

**Comment by liamwhite** [comment]
Since the regression is very recent, are you able to bisect it?

**Comment by HurricanePootis** [comment]
Yeah, do I just download a bunch of recent appimage builds and try them out? I've never bisected anything before.

**Comment by liamwhite** [comment]
Yes, find the newest one that still works, or the oldest one that exhibits the issue.

**Comment by HurricanePootis** [comment]
@liamwhite I had to go all the back to yuzu 1388 for the game load.

**Comment by liamwhite** [comment]
Could you verify if it is any of the commits in this release? https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-1389

**Comment by HurricanePootis** [comment]
@liamwhite After building yuzu 1389 without this patch https://github.com/yuzu-emu/yuzu-mainline/commit/f047ba3bc3a79490dc01a5422541766926d6a151, I was able to launch the game successfully. I don't know much about programming, so I don't know what this patch does that causes the issues, but it looks like the backtrace may have something?

**Comment by HurricanePootis** [comment]
Any more information on this?
