### ISSUE TITLE
Yuzu Unhandled SIGSEGV at rip 0x00007f18248d0250 after booting any game on Vulkan - Intel GPU

### ISSUE THREAD

**Issue by Tikilou** [yuzu-emu/yuzu#10310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3589

### Description of Issue

Hi !
I have a segfault in any case when 3D is coming, on Linux Manjaro (updated with latest kernel, driver...), and Yuzu crash too on Windows 11, after launching any game with Vulkan.
Year 2022 i was able to play to somes littles games, like Story Of Seasons, and no problem with Vulkan.
But it's working with OpenGL.

### Expected Behavior

Displaying 3D elements of any game. It's not.
In Story of Season, game doesn't crash instantly, he show loading screens and pictures with 2D, then when it's loading titlle screen with 3D environment, Yuzu crash. That's the same thing for other games.

### Reproduction Steps

Just launch any game with Vulkan render

### Log File

**Log of Yuzu in terminal :**

` $ yuzu
libpng warning: iCCP: known incorrect sRGB profile
Unhandled SIGSEGV at rip 0x00007f18248d0250
Erreur de segmentation (core dumped)
`
**Log of Yuzu with GDB :** 
`
libpng warning: iCCP: known incorrect sRGB profile
[New LWP 18214]
[New LWP 18543]
[LWP 18040 exited]
[LWP 18039 exited]
[LWP 18038 exited]
[LWP 18037 exited]
[New LWP 19221]
[New LWP 19222]
[New LWP 19224]

Thread 33 "VulkanWorker" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 18173]
0x00007f7e4acd0250 in ?? ()
(gdb) bt full
#0  0x00007f7e4acd0250 in ?? ()
No symbol table info available.
#1  0x0000000000000001 in ?? ()
No symbol table info available.
#2  0x00007f7e40e520c0 in ?? ()
No symbol table info available.
#3  0x00007f7e494fb770 in ?? ()
No symbol table info available.
#4  0x00007f7e4acd022d in ?? ()
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.
`
**(gdb) info registers :**
`
rax            0x5                 5
rbx            0x1                 1
rcx            0x7f7e447c50a0      140180291604640
rdx            0x0                 0
rsi            0x10                16
rdi            0x555557e6d190      93825035325840
rbp            0x7f7e494fb770      0x7f7e494fb770
rsp            0x7f7e494fb6f0      0x7f7e494fb6f0
r8             0x400000fb00        274877971200
r9             0x7f7e74036b00      140181088987904
r10            0x76                118
r11            0x0                 0
r12            0x7f7e447c4fb0      140180291604400
r13            0x7f7e4479fe40      140180291452480
r14            0x1                 1
r15            0x7f7e40e520c0      140180231364800
rip            0x7f7e4acd0250      0x7f7e4acd0250
eflags         0x10206             [ PF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0

`

### System Configuration

CPU: I5-7200U
GPU/Driver: HD620 / Latest drivers/mesa/kernel linux
RAM: 8Gb + 20Gb Swap dedicaced partition on 1Tb NVME SSD.
OS: Manjaro Linux with Gnome Desktop

**Comment by Squall-Leonhart** [comment]
Duplicate https://github.com/yuzu-emu/yuzu/issues/7023
