### ISSUE TITLE
Crash on running super mario odyssey

### ISSUE THREAD

**Issue by Elronnd** [yuzu-emu/yuzu#1184]
Operating system: arch linux

Version: latest git master as of this writing (be2f1eabd702b8a842270e555da39e5a8cdab482)

When I open the game up, yuzu does nothing for a while, then the window background is blackened, and then after another while it crashes.  Here is the gdb output:

```
Thread 8 "EmuThread" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7fffd955e700 (LWP 4614)]
0x00005555555f2f91 in _Z20assert_noinline_callIZN6OpenGL8GLShader10Decompiler13GLSLGenerator12CompileInstrEjEUlvE26_EvRKT_.isra.223 ()
(gdb) bt
#0  0x00005555555f2f91 in _Z20assert_noinline_callIZN6OpenGL8GLShader10Decompiler13GLSLGenerator12CompileInstrEjEUlvE26_EvRKT_.isra.223 ()
#1  0x00005555558b06fb in _ZN6OpenGL8GLShader10Decompiler13GLSLGenerator12CompileInstrEj ()
#2  0x00005555558b31d3 in _ZN6OpenGL8GLShader10Decompiler13GLSLGenerator8GenerateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE ()
#3  0x000055555589ae05 in _ZN6OpenGL8GLShader10Decompiler16DecompileProgramERKSt6vectorImSaImEEjN5Tegra7Engines9Maxwell3D4Regs11ShaderStageERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE ()
#4  0x000055555589322e in _ZN6OpenGL8GLShader20GenerateVertexShaderB5cxx11ERKNS0_11ShaderSetupERKNS0_15MaxwellVSConfigE ()
#5  0x0000555555882f04 in _ZN6OpenGL16RasterizerOpenGL12SetupShadersEPhl ()
#6  0x0000555555883e16 in _ZN6OpenGL16RasterizerOpenGL10DrawArraysEv ()
#7  0x000055555587be4a in _ZN6OpenGL16RasterizerOpenGL19AccelerateDrawBatchEb ()
#8  0x0000555555876a5a in _ZN5Tegra7Engines9Maxwell3D10DrawArraysEv ()
#9  0x00005555558772c8 in _ZN5Tegra7Engines9Maxwell3D8WriteRegEjjj ()
#10 0x000055555587844e in _ZN5Tegra16MacroInterpreter13ProcessResultENS0_15ResultOperationEjj ()
#11 0x000055555587876f in _ZN5Tegra16MacroInterpreter4StepERKSt6vectorIjSaIjEEb ()
#12 0x0000555555878a3d in _ZN5Tegra16MacroInterpreter7ExecuteERKSt6vectorIjSaIjEES3_ ()
#13 0x000055555587631d in _ZN5Tegra7Engines9Maxwell3D15CallMacroMethodEjSt6vectorIjSaIjEE ()
#14 0x00005555558771a6 in _ZN5Tegra7Engines9Maxwell3D8WriteRegEjjj ()
#15 0x00005555558755a9 in _ZN5Tegra3GPU8WriteRegEjjjj ()
#16 0x0000555555875958 in _ZN5Tegra3GPU18ProcessCommandListEmj ()
#17 0x0000555555867de0 in _ZN7Service6Nvidia7Devices10nvhost_gpu5ioctlENS1_8nvdevice5IoctlERKSt6vectorIhSaIhEERS7_ ()
#18 0x000055555586ba25 in _ZN7Service6Nvidia5NVDRV5IoctlERN6Kernel17HLERequestContextE ()
#19 0x0000555555713ae5 in _ZN7Service20ServiceFrameworkBase17HandleSyncRequestERN6Kernel17HLERequestContextE ()
#20 0x000055555579a469 in _ZN6Kernel13ServerSession17HandleSyncRequestEN5boost13intrusive_ptrINS_6ThreadEEE ()
#21 0x0000555555861376 in _ZN6Kernel13ClientSession15SendSyncRequestEN5boost13intrusive_ptrINS_6ThreadEEE ()
#22 0x000055555579c180 in _ZN6Kernel7SvcWrapIXadL_ZNS_L15SendSyncRequestEjEEEEvv ()
#23 0x000055555579d958 in _ZN6Kernel7CallSVCEj ()
#24 0x00007fffbab385eb in ?? ()
#25 0x000055555641d700 in ?? ()
#26 0x0000555555f082c0 in _ZN4Core6System10s_instanceE ()
#27 0x00007fffd955dd90 in ?? ()
#28 0x0000555556641090 in ?? ()
#29 0x00005555566408b0 in ?? ()
#30 0x0000000000000007 in ?? ()
#31 0x0000555556640850 in ?? ()
#32 0x0000555555abf318 in _ZN8Dynarmic3A643Jit3RunEv ()
#33 0x00005555556b47e3 in _ZN4Core3Cpu7RunLoopEb ()
#34 0x00005555556b25be in _ZN4Core6System7RunLoopEb ()
#35 0x00005555556327a4 in _ZN9EmuThread3runEv ()
#36 0x00007ffff660e005 in ?? () from /usr/lib/libQt5Core.so.5
#37 0x00007ffff737ca9d in start_thread () from /usr/lib/libpthread.so.0
#38 0x00007ffff6151a43 in clone () from /usr/lib/libc.so.6
```

**Comment by ReaperOfSouls1909** [comment]
use the canary build make sure multicore is off and docked is on also have sharedfonts bin and a save 
check the discord in yuzu-support for shared fonts and a save

**Comment by Elronnd** [comment]
Docked was off -- I turned it on.  I got a font file and put it in the proper location, and also a save file.  These appear to have had no effect.  Using a canary build (after making it use the system version of libsndio) seems to work, but what is the difference between it and one I compile myself?
