### ISSUE TITLE
[Super Mario Wonder/Linux] Pull Request 11894 (Merged into Mailine 1610) Causes Segfault Whenever Yuzu's Compiled With Specific Flags

### ISSUE THREAD

**Issue by HurricanePootis** [yuzu-emu/yuzu#11966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1610

### Description of Issue

I build yuzu myself, and whenever I updated from Mainline 1609 to 1610, Super Mario Wonder started to crash whenever I started the game, before anything even rendered. I looked in the console, and some something related to vulkan, and tested running the game on OpenGL—it worked perfectly.

I then began to bisect yuzu to find the issue. I eventually bisected it down to https://github.com/yuzu-emu/yuzu/pull/11894. Whenever I revert this commit on the mainline branch (https://github.com/yuzu-emu/yuzu-mainline/commit/10b1843f3e4fd661cbf8d161c620d7e0f7802134), and compile yuzu with my flags, the game doesn't crash anymore.

My flags are the following
```
CFLAGS=-march=znver3 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection
CXXFLAGS=-march=znver3 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS
```

### Expected Behavior

For the game to run even when compiled with those flags (as it has done so far).

### Reproduction Steps

```bash
#!/bin/bash
git clone https://github.com/yuzu-emu/yuzu-mainline --recursive && mkdir build
    cmake -S yuzu-mainline  -B build \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_C_COMPILER=gcc \
      -DCMAKE_CXX_COMPILER=g++ \
      -DCMAKE_C_FLAGS="-march=znver3 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection" \
      -DCMAKE_CXX_FLAGS="-march=znver3 -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS" \
      -DYUZU_ENABLE_LTO=NO \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo  \
      -DYUZU_USE_QT_WEB_ENGINE=ON \
      -DYUZU_USE_QT_MULTIMEDIA=ON \
      -DYUZU_USE_EXTERNAL_SDL2=OFF \
      -DYUZU_USE_BUNDLED_FFMPEG=OFF \
      -DYUZU_USE_BUNDLED_QT=OFF \
      -DYUZU_USE_EXTERNAL_VULKAN_HEADERS=OFF \
      -DYUZU_USE_FASTER_LD=NO \
      -DSIRIT_USE_SYSTEM_SPIRV_HEADERS=ON \
      -DYUZU_DOWNLOAD_TIME_ZONE_DATA=ON \
      -DYUZU_TESTS=OFF \
      -DENABLE_QT6=OFF \
      -DUSE_DISCORD_PRESENCE=ON \
      -DENABLE_QT_TRANSLATION=ON \
      -Wno-dev
 cmake --build build
 ```

### Log File

```
/usr/include/c++/13.2.1/array:211: constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = Tegra::Engines::Maxwell3D::Regs::RenderTargetConfig; long unsigned int _Nm = 8; const_reference = const Tegra::Engines::Maxwell3D::Regs::RenderTargetConfig&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Thread 81 "GPU" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f7c40d2c6c0 (LWP 13775)]
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                                                                                              
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fffeaeac8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fffeae5c668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fffeae444b8 in __GI_abort () at abort.c:79
#4  0x00007fffeb0dd3b2 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    (file=file@entry=0x555555f29396 "/usr/include/c++/13.2.1/array", line=line@entry=211, function=function@entry=0x555555f2ff28 "constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = Tegra::Engines::Maxwell3D::Regs::RenderTargetConfig; long unsigned int _Nm = 8; const_re"..., condition=condition@entry=0x555555ed7ac6 "__n < this->size()") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/debug.cc:61
#5  0x00005555568e1450 in std::array<Tegra::Engines::Maxwell3D::Regs::RenderTargetConfig, 8ul>::operator[](unsigned long) const (this=0x7f7dd8629ba0, __n=8)
    at /usr/include/c++/13.2.1/array:208
#6  std::array<Tegra::Engines::Maxwell3D::Regs::RenderTargetConfig, 8ul>::operator[](unsigned long) const (__n=8, this=0x7f7dd8629ba0) at /usr/include/c++/13.2.1/array:208
#7  Vulkan::(anonymous namespace)::GetViewportState(Vulkan::Maxwell const&, size_t, float, Vulkan::Device const&)
    (regs=..., index=index@entry=8, scale=scale@entry=1, device=<optimized out>) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/renderer_vulkan/vk_rasterizer.cpp:65
#8  0x00005555568e2954 in Vulkan::RasterizerVulkan::UpdateViewportsState(Tegra::Engines::Maxwell3D::Regs&) (this=this@entry=0x7f7e474f73a8, regs=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/renderer_vulkan/vk_rasterizer.cpp:971
#9  0x00005555568e5efc in Vulkan::RasterizerVulkan::Clear(unsigned int) (this=0x7f7e474f73a8, layer_count=1)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/renderer_vulkan/vk_rasterizer.cpp:345
#10 0x00005555567d93d3 in Tegra::MacroEngine::Execute(unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > const&)
    (this=<optimized out>, method=<optimized out>, parameters=std::vector of length 1, capacity 3 = {...})
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/macro/macro.cpp:122
#11 0x00005555567c3688 in Tegra::Engines::Maxwell3D::CallMacroMethod(unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > const&)
    (parameters=std::vector of length 1, capacity 3 = {...}, method=<optimized out>, this=0x7f7dd8627370)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/engines/maxwell_3d.cpp:407
#12 Tegra::Engines::Maxwell3D::ProcessMacro(unsigned int, unsigned int const*, unsigned int, bool) (this=this@entry=0x7f7dd8627370, method=<optimized out>, 
    method@entry=3586, base_start=base_start@entry=0x7f7c40d28cc8, amount=amount@entry=1, is_last_call=is_last_call@entry=true)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/engines/maxwell_3d.cpp:216
--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00005555567c4438 in Tegra::Engines::Maxwell3D::CallMethod(unsigned int, unsigned int, bool)
    (this=0x7f7dd8627370, method=<optimized out>, method_argument=<optimized out>, is_last_call=<optimized out>)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/engines/maxwell_3d.cpp:422
#14 0x00005555567accb4 in Tegra::DmaPusher::ProcessCommands(std::span<Tegra::CommandHeader const, 18446744073709551615ul>) (this=this@entry=0x7f7dd8625560, commands=Python Exception <class 'gdb.error'>: No symbol "static_cast" in current context.
...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/dma_pusher.cpp:136
#15 0x00005555567acf7e in operator()() const (__closure=__closure@entry=0x7f7c40d28e00) at /usr/include/c++/13.2.1/span:90
#16 0x00005555567ad3aa in Tegra::DmaPusher::Step() (this=this@entry=0x7f7dd8625560) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/dma_pusher.cpp:114
#17 0x00005555567ad8d8 in Tegra::DmaPusher::DispatchCalls() (this=0x7f7dd8625560) at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/dma_pusher.cpp:36
#18 0x00005555567ab546 in Tegra::Control::Scheduler::Push(int, Tegra::CommandList&&) (this=0x7f7e90000b90, channel=<optimized out>, entries=...)
    at /usr/include/c++/13.2.1/bits/unique_ptr.h:199
#19 0x00005555567e5e1a in VideoCommon::GPUThread::RunThread(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GPUThread::SynchState&) (stop_token=..., system=<optimized out>, renderer=<optimized out>, context=<optimized out>, scheduler=<optimized out>, state=...)
    at /home/hurricane/yuzu-mainline-git/src/yuzu/src/video_core/gpu_thread.cpp:42
#20 0x00005555567e62d6 in std::__invoke_impl<void, void (*)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GPUThread::SynchState&), std::stop_token, std::reference_wrapper<Core::System>, std::reference_wrapper<VideoCore::RendererBase>, std::reference_wrapper<Core::Frontend::GraphicsContext>, std::reference_wrapper<Tegra::Control::Scheduler>, std::reference_wrapper<VideoCommon::GPUThread::SynchState> >(std::__invoke_other, void (*&&)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GPUThread::SynchState&), std::stop_token&&, std::reference_wrapper<Core::System>&&, std::reference_wrapper<VideoCore::RendererBase>&&, std::reference_wrapper<Core::Frontend::GraphicsContext>&&, std::reference_wrapper<Tegra::Control::Scheduler>&&, std::reference_wrapper<VideoCommon::GPUThread::SynchState>&&) (__f=<optimized out>) at /usr/include/c++/13.2.1/stop_token:414
#21 std::__invoke<void (*)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GPUThread::SynchState&), std::stop_token, std::reference_wrapper<Core::System>, std::reference_wrapper<VideoCore::RendererBase>, std::reference_wrapper<Core::Frontend::GraphicsContext>, std::reference_wrapper<Tegra::Control::Scheduler>, std::reference_wrapper<VideoCommon::GPUThread::SynchState> >(void (*&&)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GPUThread::SynchState&), std::stop_token&&, std::reference_wrapper<Core::System>&&, std::reference_wrapper<VideoCore::RendererBase>&&, std::reference_wrapper<Core::Frontend::GraphicsContext>&&, std::reference_wrapper<Tegra::Control::Scheduler>&&, std::reference_wrapper<VideoCommon::GPUThread::SynchState>&&) (__fn=<optimized out>) at /usr/include/c++/13.2.1/bits/invoke.h:96
#22 std::thread::_Invoker<std::tuple<void (*)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GP--Type <RET> for more, q to quit, c to continue without paging--
UThread::SynchState&), std::stop_token, std::reference_wrapper<Core::System>, std::reference_wrapper<VideoCore::RendererBase>, std::reference_wrapper<Core::Frontend::GraphicsContext>, std::reference_wrapper<Tegra::Control::Scheduler>, std::reference_wrapper<VideoCommon::GPUThread::SynchState> > >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>) (this=<optimized out>) at /usr/include/c++/13.2.1/bits/std_thread.h:292
#23 std::thread::_Invoker<std::tuple<void (*)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GPUThread::SynchState&), std::stop_token, std::reference_wrapper<Core::System>, std::reference_wrapper<VideoCore::RendererBase>, std::reference_wrapper<Core::Frontend::GraphicsContext>, std::reference_wrapper<Tegra::Control::Scheduler>, std::reference_wrapper<VideoCommon::GPUThread::SynchState> > >::operator()() (this=<optimized out>)
    at /usr/include/c++/13.2.1/bits/std_thread.h:299
#24 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::Control::Scheduler&, VideoCommon::GPUThread::SynchState&), std::stop_token, std::reference_wrapper<Core::System>, std::reference_wrapper<VideoCore::RendererBase>, std::reference_wrapper<Core::Frontend::GraphicsContext>, std::reference_wrapper<Tegra::Control::Scheduler>, std::reference_wrapper<VideoCommon::GPUThread::SynchState> > > >::_M_run() (this=<optimized out>)
    at /usr/include/c++/13.2.1/bits/std_thread.h:244
#25 0x00007fffeb0e1943 in std::execute_native_thread_routine(void*) (__p=0x55555850eb50) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#26 0x00007fffeaeaa9eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#27 0x00007fffeaf2e7cc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

### System Configuration

CPU: Ryzen 5 5625U
GPU/Driver: AMD Radeon Graphics (GCN5 based iGPU)
RAM: 16GB
OS: Arch Linux

**Comment by HurricanePootis** [comment]
Using this https://github.com/yuzu-emu/yuzu/compare/1a5203d05eefb72e9595c24f7efe4a6bf23dc055..5e06f8ff078724a0f2b0fb5a4c0d7b0404909234 patch that @liamwhite made in the discord fixes the problem on my end.

**Comment by liamwhite** [comment]
Fixed in latest mainline

**Comment by HurricanePootis** [comment]
Thank you!
