### ISSUE TITLE
svcSignalProcessWideKey segfaults

### ISSUE THREAD

**Issue by Drakulix** [yuzu-emu/yuzu#1239]
Version: dda4b5e
Backtrace:
```
[  17.753550] Kernel.SVC <Trace> core/hle/kernel/svc.cpp:SignalProcessWideKey:642: called, condition_variable_addr=0x5FFFFFD8, target=0x00000001
(gdb) bt
#0  0x0000000000536241 in void Kernel::SvcWrap<&Kernel::SignalProcessWideKey>() ()
#1  0x00000000005348a3 in Kernel::CallSVC(unsigned int) ()
#2  0x00000000004c580b in Core::InterruptHook(uc_struct*, unsigned int, void*) ()
#3  0x000000000069feeb in cpu_arm_exec_aarch64 (uc=0x10f4500, env=0x10aebe8)
    at /storage/Projects/NintendoSwitch/yuzu/externals/unicorn/qemu/cpu-exec.c:134
#4  0x00000000006a0a35 in tcg_cpu_exec_aarch64 (uc=0x10f4500, env=0x10aebe8)
    at /storage/Projects/NintendoSwitch/yuzu/externals/unicorn/qemu/cpus.c:120
#5  0x00000000006a0a9c in tcg_exec_all_aarch64 (uc=0x10f4500)
    at /storage/Projects/NintendoSwitch/yuzu/externals/unicorn/qemu/cpus.c:135
#6  0x00000000006a09cc in qemu_tcg_cpu_loop (uc=0x10f4500)
    at /storage/Projects/NintendoSwitch/yuzu/externals/unicorn/qemu/cpus.c:102
#7  0x00000000006a0930 in resume_all_vcpus_aarch64 (uc=0x10f4500)
    at /storage/Projects/NintendoSwitch/yuzu/externals/unicorn/qemu/cpus.c:76
#8  0x00000000006a0870 in vm_start_aarch64 (uc=0x10f4500)
    at /storage/Projects/NintendoSwitch/yuzu/externals/unicorn/qemu/cpus.c:46
#9  0x000000000068b737 in uc_emu_start (uc=0x10f4500, begin=134245504, 
    until=9223372036854775808, timeout=0, count=20000) at ../uc.c:615
#10 0x00000000004c5fa5 in Core::ARM_Unicorn::ExecuteInstructions(int) ()
#11 0x0000000000479e13 in Core::Cpu::RunLoop(bool) ()
#12 0x0000000000478fc7 in Core::System::Impl::RunLoop(bool) ()
#13 0x000000000043d8a6 in main ()
```

I have no idea, why gdb is not able to pin down the exact line, but I have minimal example, 
because I am using yuzu for homebrew development. The following code runs finde on actual hardware and is a modification of [this project](https://github.com/switchbrew/switch-examples/tree/master/graphics/printing/hello-world).
Just replace the main.c and run `make` using devkitpro.

```c
#include <string.h>
#include <stdio.h>

#include <switch.h>

static void thread_main(void *args) {
    CondVar *c = (CondVar *)args;
    svcSleepThread(10000000000);
    condvarWakeOne(c);
}

int main(int argc, char **argv)
{
    gfxInitDefault();
    consoleInit(NULL);
    printf("Hello World!\n");
    
    printf("Spawning thread...\n");
    Thread thread;
    CondVar c;
    Mutex m;
    condvarInit(&c);
    mutexInit(&m);
    threadCreate(&thread, &thread_main, &c, 4096, 0x3B, -2);
    threadStart(&thread);
    
    printf("Parking...\n");
    condvarWait(&c, &m);
    printf("Unparked!\n");
    
    threadClose(&thread);
    
    while(appletMainLoop())
    {
        hidScanInput();
        u64 kDown = hidKeysDown(CONTROLLER_P1_AUTO);

        if (kDown & KEY_PLUS) break; // break in order to return to hbmenu

        gfxFlushBuffers();
        gfxSwapBuffers();
        gfxWaitForVsync();
    }

    gfxExit();
    return 0;
}
```

**Comment by Hexagon12** [comment]
Why are you using... Unicorn...? It's deprecated and you should use Dynarmic by setting the CPU JIT on in Emulation - Configure via Yuzu's UI.

**Comment by Drakulix** [comment]
> Why are you using... Unicorn...? It's deprecated and you should use Dynarmic by setting the CPU JIT on in Emulation - Configure via Yuzu's UI.

Because the GDBStub is even less functional using Dynarmic. While gdb mostly works, radare2, which really helped me to identify some very complicated bugs, is failing reading the registers. I do not know, why it is different, but Unicorn is working nicely otherwise. Also I was not aware that Unicorn is now deprecated.

**Comment by Hexagon12** [comment]
Is the issue still present with the latest master? I would suggest making a new issue which targets as a bug in Dynarmic, since we're planning to remove some parts of Unicorn (it was never intended to be the main interpreter, just a fallback one).

**Comment by MysticExile** [comment]
Again asking if this issue is still present on the latest master. I would really like an update on this issue.

**Comment by MysticExile** [comment]
It does not seem like this is a relevant issue anymore due to us moving to Dynarmic, if you still believe this is applicable, please open a new issue. Thank you!
