### ISSUE TITLE
Broken linked list implementation in "KSynchronizationObject"

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [yuzu-emu/yuzu#12899]
### Issue

Hi, I am experiencing some memory corruption issue when developing a WebSession related feature for yuzu.

I then compiled yuzu with address-sanitizer and found the following suspicious code snippet:

https://github.com/yuzu-emu/yuzu/blob/6baf965777145fd9c76bd06a3c140afa46a50e87/src/core/hle/kernel/k_synchronization_object.h#L47-L66

In the `UnlinkNode` function, I don't understand why `std::addressof(m_thread_list_head)` (should be `ThreadListNode**`) is reinterpret_cast to `ThreadListNode*`. It also doesn't handle the case that the head node gets unlinked.

Anyway, this code looks weird, although maybe I don't understand the context.

**Comment by liamwhite** [comment]
I see no reason unlinking the head wouldn't work (the head node is a `ThreadListNode*`, the first iteration runs it through with a `ThreadListNode**` pointing to the head node), though this code does violate strict aliasing rules. If you want a version that does no aliasing and is more obviously correct, here is one:
```cpp
void KSynchronizationObject::UnlinkNode(ThreadListNode *node) {
    /* If the node was the head, update it. */
    if (thread_list_head == node) {
        thread_list_head = node->next;

        /* If the node was also the tail, the list is now empty. */
        if (thread_list_tail == node) {
            thread_list_tail = nullptr;
        }
    } else {
        /* Otherwise, find the previous node. */
        auto *prev = thread_list_head;
        while (prev->next != node) {
            prev = prev->next;
        }

        /* Update the previous's next. */
        prev->next = node->next;

        /* If the node was the tail, update the tail. */
        if (thread_list_tail == node) {
            thread_list_tail = prev;
        }
    }
}
```

Otherwise, please provide a sample where this breaks.

**Comment by Alkaid-Benetnash** [comment]
Attaching the report from address-sanitizer here:
It basically says `Kernel::KSynchronizationObject::NotifyAvailable` accessed an address on the stack that it is not supposed to access. The accessed address is known to be out-of-scope/invalid and now belongs to another function call running on another thread.
```
=================================================================
==187037==ERROR: AddressSanitizer: stack-use-after-return on address 0x77515bd25048 at pc 0x5d8ad2a9e64e bp 0x77d280ea8590 sp 0x77d280ea8588
READ of size 8 at 0x77515bd25048 thread T37
    #0 0x5d8ad2a9e64d in Kernel::KSynchronizationObject::NotifyAvailable(Result) yuzu/src/core/hle/kernel/k_synchronization_object.cpp:162:19
    #1 0x5d8ad2b57402 in Kernel::KSynchronizationObject::NotifyAvailable() yuzu/src/core/hle/kernel/k_synchronization_object.h:76:22
    #2 0x5d8ad2b57402 in Kernel::KServerPort::EnqueueSession(Kernel::KServerSession*) yuzu/src/core/hle/kernel/k_server_port.cpp:103:15
    #3 0x5d8ad2b55257 in Kernel::KPort::EnqueueSession(Kernel::KServerSession*) yuzu/src/core/hle/kernel/k_port.cpp:57:14
    #4 0x5d8ad2b51de7 in Kernel::KClientPort::CreateSession(Kernel::KClientSession**) yuzu/src/core/hle/kernel/k_client_port.cpp:116:5
    #5 0x5d8ad3261c94 in Service::SM::SM::GetServiceImpl(Kernel::KClientSession**, Service::HLERequestContext&) yuzu/src/core/hle/service/sm/sm.cpp:194:42
    #6 0x5d8ad3261037 in Service::SM::SM::GetServiceCmif(Service::HLERequestContext&) yuzu/src/core/hle/service/sm/sm.cpp:130:19
    #7 0x5d8ad2fb85c6 in Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::KServerSession&, Service::HLERequestContext&) yuzu/src/core/hle/service/service.cpp
    #8 0x5d8ad2f8d440 in Service::SessionRequestManager::CompleteSyncRequest(Kernel::KServerSession*, Service::HLERequestContext&) yuzu/src/core/hle/service/hle_ipc.cpp:78:45
    #9 0x5d8ad2fafccb in Service::ServerManager::CompleteSyncRequest(Service::ServerManager::RequestState&&) yuzu/src/core/hle/service/server_manager.cpp:398:35
    #10 0x5d8ad2fad2d8 in Service::ServerManager::OnSessionEvent(Kernel::KServerSession*, std::shared_ptr<Service::SessionRequestManager>&&) yuzu/src/core/hle/service/server_manager.cpp:387:5
    #11 0x5d8ad2fa9eaa in Service::ServerManager::WaitAndProcessImpl() yuzu/src/core/hle/service/server_manager.cpp:308:13
    #12 0x5d8ad2fa79da in Service::ServerManager::LoopProcessImpl() yuzu/src/core/hle/service/server_manager.cpp:196:9
    #13 0x5d8ad2fa79da in Service::ServerManager::LoopProcess() yuzu/src/core/hle/service/server_manager.cpp:191:5
    #14 0x5d8ad32666dd in Core::System::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager>>&&) yuzu/src/core/core.cpp:990:25
    #15 0x5d8ad32666dd in Service::ServerManager::RunServer(std::unique_ptr<Service::ServerManager, std::default_delete<Service::ServerManager>>&&) yuzu/src/core/hle/service/server_manager.cpp:75:30
    #16 0x5d8ad32666dd in Service::SM::LoopProcess(Core::System&) yuzu/src/core/hle/service/sm/sm.cpp:285:5
    #17 0x5d8ad2abf930 in std::function<void ()>::operator()() const /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:591:9
    #18 0x5d8ad2abf930 in Kernel::KThread::InitializeServiceThread(Core::System&, Kernel::KThread*, std::function<void ()>&&, int, int, Kernel::KProcess*)::$_0::operator()() const yuzu/src/core/hle/kernel/k_thread.cpp:313:9
    #19 0x5d8ad2abf930 in void std::__invoke_impl<void, Kernel::KThread::InitializeServiceThread(Core::System&, Kernel::KThread*, std::function<void ()>&&, int, int, Kernel::KProcess*)::$_0&>(std::__invoke_other, Kernel::KThread::InitializeServiceThread(Core::System&, Kernel::KThread*, std::function<void ()>&&, int, int, Kernel::KProcess*)::$_0&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:61:14
    #20 0x5d8ad2abf930 in std::enable_if<is_invocable_r_v<void, Kernel::KThread::InitializeServiceThread(Core::System&, Kernel::KThread*, std::function<void ()>&&, int, int, Kernel::KProcess*)::$_0&>, void>::type std::__invoke_r<void, Kernel::KThread::InitializeServiceThread(Core::System&, Kernel::KThread*, std::function<void ()>&&, int, int, Kernel::KProcess*)::$_0&>(Kernel::KThread::InitializeServiceThread(Core::System&, Kernel::KThread*, std::function<void ()>&&, int, int, Kernel::KProcess*)::$_0&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/invoke.h:111:2
    #21 0x5d8ad2abf930 in std::_Function_handler<void (), Kernel::KThread::InitializeServiceThread(Core::System&, Kernel::KThread*, std::function<void ()>&&, int, int, Kernel::KProcess*)::$_0>::_M_invoke(std::_Any_data const&) /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/bits/std_function.h:290:9
    #22 0x5d8ad26b5b3b in Common::Fiber::Start(boost::context::detail::transfer_t&) yuzu/src/common/fiber.cpp:44:5
    #23 0x5d8ad26b5b3b in Common::Fiber::FiberStartFunc(boost::context::detail::transfer_t) yuzu/src/common/fiber.cpp:61:12
    #24 0x77d2c7136156 in make_fcontext (/usr/lib/libboost_context.so.1.83.0+0x1156) (BuildId: 31e0d8fb2b3e80ae2d570bdddeab85d547b333b5)

Address 0x77515bd25048 is located in stack of thread T37 at offset 72 in frame
    #0 0x5d8ad27c1fef in FileSys::NcaFileSystemDriver::CreateIntegrityVerificationStorageImpl(std::shared_ptr<FileSys::VfsFile>*, std::shared_ptr<FileSys::VfsFile>, FileSys::NcaFsHeader::HashData::IntegrityMetaInfo const&, long, int, int, signed char) yuzu/src/core/file_sys/fssystem/fssystem_nca_file_system_driver.cpp:1211

  This frame has 16 object(s):
    [32, 36) 'index.addr.i'
    [48, 56) 'ref.tmp.i'
    [80, 88) 'out.addr' <== Memory access at offset 72 underflows this variable
    [112, 120) 'layer_info_offset.addr'
    [144, 152) 'ref.tmp' (line 1213)
    [176, 184) 'ref.tmp2' (line 1214)
    [208, 216) 'ref.tmp3' (line 1215)
    [240, 420) 'level_hash_info' (line 1222)
    [496, 608) 'storage_info' (line 1235)
    [640, 656) 'ref.tmp33' (line 1241)
    [672, 680) 'ref.tmp35' (line 1241)
    [704, 712) 'last_layer_info_offset' (line 1247)
    [736, 752) 'integrity_storage' (line 1258)
    [768, 948) 'agg.tmp112'
    [1024, 1056) 'agg.tmp113'
    [1088, 1200) 'agg.tmp114'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T37 created by T0 here:
    #0 0x5d8ad1d395d8 in pthread_create (build/bin/yuzu+0x11085d8) (BuildId: d34e7d53884a8d12)
    #1 0x77d2b74e1a29 in __gthread_create /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:663:35
    #2 0x77d2b74e1a29 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State>>, void (*)()) /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:172:37
    #3 0x5d8ad269d081 in Core::System::Impl::InitializeKernel(Core::System&) yuzu/src/core/core.cpp:247:21
    #4 0x5d8ad269d081 in Core::System::Impl::Load(Core::System&, Core::Frontend::EmuWindow&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned long, unsigned long) yuzu/src/core/core.cpp:299:9
    #5 0x5d8ad2451085 in Core::System::Load(Core::Frontend::EmuWindow&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, unsigned long, unsigned long) yuzu/src/core/core.cpp:638:18
    #6 0x5d8ad2451085 in GMainWindow::LoadROM(QString const&, unsigned long, unsigned long, AmLaunchType) yuzu/src/yuzu/main.cpp:1815:17
    #7 0x5d8ad24042a9 in GMainWindow::BootGame(QString const&, unsigned long, unsigned long, StartGameType, AmLaunchType) yuzu/src/yuzu/main.cpp:1987:10
    #8 0x5d8ad24916b3 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<QString const&, unsigned long>, void, void (GMainWindow::*)(QString, unsigned long)>::call(void (GMainWindow::*)(QString, unsigned long), GMainWindow*, void**) /usr/include/qt6/QtCore/qobjectdefs_impl.h:145:13
    #9 0x5d8ad24916b3 in void QtPrivate::FunctionPointer<void (GMainWindow::*)(QString, unsigned long)>::call<QtPrivate::List<QString const&, unsigned long>, void>(void (GMainWindow::*)(QString, unsigned long), GMainWindow*, void**) /usr/include/qt6/QtCore/qobjectdefs_impl.h:182:13
    #10 0x5d8ad24916b3 in QtPrivate::QCallableObject<void (GMainWindow::*)(QString, unsigned long), QtPrivate::List<QString const&, unsigned long>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) /usr/include/qt6/QtCore/qobjectdefs_impl.h:520:21
    #11 0x77d2b79b9ec8  (/usr/lib/libQt6Core.so.6+0x1b9ec8) (BuildId: cb022489bffbb1eff08dc837c4e1efc95941a304)

SUMMARY: AddressSanitizer: stack-use-after-return yuzu/src/core/hle/kernel/k_synchronization_object.cpp:162:19 in Kernel::KSynchronizationObject::NotifyAvailable(Result)
Shadow bytes around the buggy address:
  0x77515bd24d80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd24e00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd24e80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd24f00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd24f80: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x77515bd25000: f5 f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5
  0x77515bd25080: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd25100: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd25180: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd25200: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x77515bd25280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==187037==ABORTING

```

**Comment by liamwhite** [comment]
NotifyAvailable broke because a KThread woke up and started running before it was marked as runnable (probably you are holding the scheduler lock recursively when performing a suspend, which is not allowed). I am going to close this issue as I cannot reasonably audit the code changes you have made for correctness to the kernel requirements...

**Comment by liamwhite** [comment]
This ASan report looks like it may be a false positive too, because we do have a custom thread context switcher, and those are known to interact poorly with both ASan and valgrind.

**Comment by Alkaid-Benetnash** [comment]
I was wrong.
After reading it more and following your discussions on discord, that code is fine. I need to continue triage the memory corruption.

I didn't modify any kernel code though, I was only playing with the web applet, qtwebengine stuff.

Also thanks for the info that ASan is not expected to work well here.
