### ISSUE TITLE
[Linux][AMDGPU] Astral Chain booting fails on EA builds (exact source issue included)

### ISSUE THREAD

**Issue by RealJohnGalt** [yuzu-emu/yuzu#3972]
**Specs:**
```
System:    Host: miniarch Kernel: 5.7.0-rc6-1-tkg-pds x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: KDE Plasma 5.18.5 
           tk: Qt 5.14.2 wm: kwin_x11 dm: SDDM Distro: Arch Linux 
CPU:       Topology: 6-Core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen 2 L2 cache: 3072 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 103197 
           Speed: 4298 MHz min/max: 2200/4300 MHz Core speeds (MHz): 1: 4299 2: 4295 3: 4297 4: 4292 5: 4299 6: 4300 7: 4300 
           8: 4300 9: 4293 10: 4298 11: 4295 12: 4290 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] vendor: XFX Pine 
           driver: amdgpu v: kernel bus ID: 26:00.0 chip ID: 1002:67df 
           Display: x11 server: X.Org 1.20.8 compositor: kwin_x11 driver: amdgpu unloaded: fbdev,modesetting,vesa 
           alternate: ati resolution: 1: 3840x2160~60Hz 2: 2560x1440~60Hz s-dpi: 96 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.37.0 5.7.0-rc6-1-tkg-pds LLVM 11.0.0) 
           v: 4.6 Mesa 20.2.0-devel (git-8635c28a92) direct render: Yes
```

For awhile now, Astral Chain has been failing to boot on EA builds on Linux. The log is cut off at the crash, so there's nothing worthwhile in it.

However, I found the issue lies in the EA change in src/core/hle/kernel/thread.cpp of context.fpcr = 0. 

I know this is supposed to improve the softlock situation, however reverting to context.fpcr = 0x03C00000 fixes astral chain booting with no other source changes.

**Backtrace:**
```
0x00007ffff61312e5 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff61312e5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff611a853 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff64b386a in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff64bfd8a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff64bfdf7 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x0000555555d66bb8 in Dynarmic::Common::Terminate (msg=..., args=...)
    at /home/cody/source/yuzu-linux-downloader/yuzu-windows-msvc-source-20200521-d54769549/externals/dynarmic/src/common/assert.cpp:16
#6  0x0000555555d61786 in Dynarmic::Common::detail::TerminateHelper<>(fmt::v6::basic_string_view<char>) (msg=...) at /usr/include/fmt/core.h:1581
#7  0x0000555555de386e in operator() (__closure=<optimized out>) at /usr/include/c++/10.1.0/bits/char_traits.h:357
#8  Dynarmic::Backend::X64::RegAlloc::CopyToScratch (this=<optimized out>, bit_width=<optimized out>, to=<optimized out>, from=<optimized out>)
    at /home/cody/source/yuzu-linux-downloader/yuzu-windows-msvc-source-20200521-d54769549/externals/dynarmic/src/backend/x64/reg_alloc.cpp:545
#9  0x0000555555de39d6 in Dynarmic::Backend::X64::RegAlloc::UseScratchImpl (this=this@entry=0x55555870ec00, use_value=..., 
    desired_locations=std::vector of length 1, capacity 1 = {...})
    at /home/cody/source/yuzu-linux-downloader/yuzu-windows-msvc-source-20200521-d54769549/externals/dynarmic/src/backend/x64/reg_alloc.cpp:373
#10 0x0000555555de3bfb in Dynarmic::Backend::X64::RegAlloc::UseScratch (this=0x55555870ec00, arg=..., host_loc=1483794576) at /usr/include/c++/10.1.0/bits/stl_algobase.h:560
#11 0x0000555555de3e59 in Dynarmic::Backend::X64::RegAlloc::HostCall (this=0x55555870ec00, result_def=0x55555870e938, result_def@entry=0x0, 
    arg0=std::optional<std::reference_wrapper<Dynarmic::Backend::X64::Argument>> [no contained value], 
    arg1=std::optional<std::reference_wrapper<Dynarmic::Backend::X64::Argument>> = {...}, 
    arg2=std::optional<std::reference_wrapper<Dynarmic::Backend::X64::Argument>> [no contained value], 
    arg3=std::optional<std::reference_wrapper<Dynarmic::Backend::X64::Argument>> [no contained value]) at /usr/include/c++/10.1.0/bits/refwrap.h:337
#12 0x0000555555e03aff in Dynarmic::Backend::X64::A64EmitX64::EmitA64ExclusiveReadMemory128 (this=0x7fff64081fe8, ctx=..., inst=0x7ffd063597f8)
    at /usr/include/c++/10.1.0/optional:691
#13 0x0000555555e08658 in Dynarmic::Backend::X64::A64EmitX64::Emit (this=this@entry=0x7fff64081fe8, block=...)
    at /home/cody/source/yuzu-linux-downloader/yuzu-windows-msvc-source-20200521-d54769549/externals/dynarmic/src/./frontend/ir/opcodes.inc:649
#14 0x0000555555d66958 in Dynarmic::A64::Jit::Impl::GetBlock (this=0x7fff64080e50, current_location=...)
    at /home/cody/source/yuzu-linux-downloader/yuzu-windows-msvc-source-20200521-d54769549/externals/dynarmic/src/backend/x64/a64_interface.cpp:257

```

**Comment by RealJohnGalt** [comment]
Fixed by https://github.com/MerryMage/dynarmic/commit/2169653c50e1c182c29a2e00e3f695db01295f2e
