### ISSUE TITLE
Segfault when stopping emulation

### ISSUE THREAD

**Issue by v1993** [yuzu-emu/yuzu#6630]
I'm getting segfault when stopping emulation on recent builds (KUbuntu 21.04). Interestingly, there actually seem to be at least two *different* segfaults (one in `EmuControl` thread and another in `HleService`), but I was only able to capture backtrace for the second one:

```
#0  VideoCommon::GPUThread::ThreadManager::PushCommand(std::variant<VideoCommon::GPUThread::EndProcessingCommand, VideoCommon::GPUThread::SubmitListCommand, VideoCommon::GPUThread::SwapBuffersCommand, VideoCommon::GPUThread::FlushRegionCommand, VideoCommon::GPUThread::InvalidateRegionCommand, VideoCommon::GPUThread::FlushAndInvalidateRegionCommand, VideoCommon::GPUThread::OnCommandListEndCommand, VideoCommon::GPUThread::GPUTickCommand>&&, bool) [clone .isra.0]
    (this=0x1a80, command_data=..., block=block@entry=false) at ../src/video_core/gpu_thread.cpp:147
#1  0x0000560bfbf815bf in VideoCommon::GPUThread::ThreadManager::SubmitList(Tegra::CommandList&&) (this=<optimized out>, entries=<optimized out>) at ../src/video_core/gpu_thread.cpp:89
#2  0x0000560bfbf3b6e6 in Tegra::GPU::PushGPUEntries(Tegra::CommandList&&) (entries=..., this=0x0) at ../src/video_core/gpu.cpp:490
#3  Service::Nvidia::Devices::nvhost_gpu::SubmitGPFIFOImpl(Service::Nvidia::Devices::nvhost_gpu::IoctlSubmitGpfifo&, std::vector<unsigned char, std::allocator<unsigned char> >&, Tegra::CommandList&&)
    (this=0x560bfff4b550, params=..., output=std::vector of length 24, capacity 24 = {...}, entries=...) at ../src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp:246
#4  0x0000560bfbf3bc88 in Service::Nvidia::Devices::nvhost_gpu::SubmitGPFIFOBase(std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&) (output=std::vector of length 24, capacity 24 = {...}, input_inline=std::vector of length 0, capacity 0, input=<optimized out>, this=0x560bfff4b550)
    at ../src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp:294
#5  Service::Nvidia::Devices::nvhost_gpu::Ioctl2(int, Service::Nvidia::Ioctl, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&) (this=0x560bfff4b550, fd=<optimized out>, command=..., input=<optimized out>, inline_input=std::vector of length 0, capacity 0, output=std::vector of length 24, capacity 24 = {...})
    at ../src/core/hle/service/nvdrv/devices/nvhost_gpu.cpp:84
#6  0x0000560bfbe91bb2 in Service::Nvidia::Module::Ioctl2(int, Service::Nvidia::Ioctl, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> > const&, std::vector<unsigned char, std::allocator<unsigned char> >&)
    (output=std::vector of length 24, capacity 24 = {...}, inline_input=std::vector of length 232, capacity 232 = {...}, input=std::vector of length 24, capacity 24 = {...}, command=..., fd=4, this=<optimized out>)
    at ../src/core/hle/service/nvdrv/nvdrv.cpp:133
#7  Service::Nvidia::NVDRV::Ioctl2(Kernel::HLERequestContext&) (this=<optimized out>, ctx=...) at ../src/core/hle/service/nvdrv/interface.cpp:102
#8  0x0000560bfbe992db in Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::KServerSession&, Kernel::HLERequestContext&) (this=0x560bfed61ec0, session=..., ctx=...) at ../src/core/hle/service/service.cpp:212
#9  0x0000560bfbeeba79 in Kernel::KServerSession::CompleteSyncRequest(Kernel::HLERequestContext&) (this=0x7f891c2c5780, context=...) at ../src/core/hle/kernel/k_server_session.cpp:160
#10 0x0000560bfbe22329 in operator() (__closure=0x7f08060d2e40) at ../src/core/hle/kernel/service_thread.cpp:88
#11 std::__invoke_impl<void, Kernel::ServiceThread::Impl::QueueSyncRequest(Kernel::KSession&, std::shared_ptr<Kernel::HLERequestContext>&&)::<lambda()>&> (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#12 std::__invoke_r<void, Kernel::ServiceThread::Impl::QueueSyncRequest(Kernel::KSession&, std::shared_ptr<Kernel::HLERequestContext>&&)::<lambda()>&> (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#13 std::_Function_handler<void(), Kernel::ServiceThread::Impl::QueueSyncRequest(Kernel::KSession&, std::shared_ptr<Kernel::HLERequestContext>&&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=<optimized out>)
    at /usr/include/c++/11/bits/std_function.h:291
#14 0x0000560bfbe3099e in std::function<void ()>::operator()() const (this=0x7f0747e8f5f0) at /usr/include/c++/11/bits/std_function.h:560
#15 operator() (__closure=0x560bfff4bcc8) at ../src/core/hle/kernel/service_thread.cpp:67
#16 std::__invoke_impl<void, Kernel::ServiceThread::Impl::Impl(Kernel::KernelCore&, std::size_t, const string&)::<lambda()> > (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#17 std::__invoke<Kernel::ServiceThread::Impl::Impl(Kernel::KernelCore&, std::size_t, const string&)::<lambda()> > (__fn=...) at /usr/include/c++/11/bits/invoke.h:96
#18 std::thread::_Invoker<std::tuple<Kernel::ServiceThread::Impl::Impl(Kernel::KernelCore&, std::size_t, const string&)::<lambda()> > >::_M_invoke<0> (this=0x560bfff4bcc8) at /usr/include/c++/11/bits/std_thread.h:253
#19 std::thread::_Invoker<std::tuple<Kernel::ServiceThread::Impl::Impl(Kernel::KernelCore&, std::size_t, const string&)::<lambda()> > >::operator() (this=0x560bfff4bcc8) at /usr/include/c++/11/bits/std_thread.h:260
#20 std::thread::_State_impl<std::thread::_Invoker<std::tuple<Kernel::ServiceThread::Impl::Impl(Kernel::KernelCore&, std::size_t, const string&)::<lambda()> > > >::_M_run(void) (this=0x560bfff4bcc0)
    at /usr/include/c++/11/bits/std_thread.h:211
#21 0x00007f894f7a0694 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#22 0x00007f8950565450 in start_thread (arg=0x7f0747e90640) at pthread_create.c:473
#23 0x00007f894f486d53 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

It doesn't seem to happen in debug build (sigh), but does happen in RelWithDebInfo one. This specific segfault appears to happen only when stopping emulation for the second time, but I may be wrong. It happens without Hades merged in as well.

I'll be happy to provide full core dumps (along with executables of course) if needed.

**Comment by german77** [comment]
Video core often fails to finalize correctly. I have this problem as well

**Comment by v1993** [comment]
Another possibly interesting wall of text - excerpt from running yuzu in valgrind (beware - it's REALLY slow, games take tens of minutes to start rendering anything and run at 4+ seconds per frame).

```
==66567== Thread 219 yuzu:EmuControl:
==66567== Invalid read of size 4
==66567==    at 0x412C4D: Kernel::KProcess::Finalize() (atomic_base.h:481)
==66567==    by 0x3C2BFB: Core::System::Impl::Shutdown() (kernel.cpp:96)
==66567==    by 0x2C2748: UnknownInlinedFun (core.cpp:457)
==66567==    by 0x2C2748: EmuThread::run() (bootmanager.cpp:117)
==66567==    by 0x7495340: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.2)
==66567==    by 0x6C8D44F: start_thread (pthread_create.c:473)
==66567==    by 0x7DBED52: clone (clone.S:95)
==66567==  Address 0x13dce958 is 27,864 bytes inside a block of size 28,184 free'd
==66567==    at 0x4845B0F: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==66567==    by 0x48D7D9: Service::NVFlinger::NVFlinger::~NVFlinger() (unique_ptr.h:85)
==66567==    by 0x3C2727: Core::System::Impl::Shutdown() (unique_ptr.h:85)
==66567==    by 0x2C2748: UnknownInlinedFun (core.cpp:457)
==66567==    by 0x2C2748: EmuThread::run() (bootmanager.cpp:117)
==66567==    by 0x7495340: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.2)
==66567==    by 0x6C8D44F: start_thread (pthread_create.c:473)
==66567==    by 0x7DBED52: clone (clone.S:95)
==66567==  Block was alloc'd at
==66567==    at 0x4842FB3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==66567==    by 0x492C7B: Service::NVFlinger::NVFlinger::CreateLayerAtId(Service::VI::Display&, unsigned long) (unique_ptr.h:962)
==66567==    by 0x4931C0: Service::NVFlinger::NVFlinger::CreateLayer(unsigned long) (nvflinger.cpp:142)
==66567==    by 0x42D768: Service::AM::ISelfController::CreateManagedDisplayLayer(Kernel::HLERequestContext&) (am.cpp:472)
==66567==    by 0x4972DA: Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::KServerSession&, Kernel::HLERequestContext&) (hle_ipc.cpp:212)
==66567==    by 0x4EA04B: Kernel::KServerSession::CompleteSyncRequest(Kernel::HLERequestContext&) (k_server_session.cpp:102)
==66567==    by 0x420328: std::_Function_handler<void (), Kernel::ServiceThread::Impl::QueueSyncRequest(Kernel::KSession&, std::shared_ptr<Kernel::HLERequestContext>&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.0] (service_thread.cpp:88)
==66567==    by 0x42E99D: std::thread::_State_impl<std::thread::_Invoker<std::tuple<Kernel::ServiceThread::Impl::Impl(Kernel::KernelCore&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}> > >::_M_run() (std_function.h:560)
==66567==    by 0x79FD693: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29)
==66567==    by 0x6C8D44F: start_thread (pthread_create.c:473)
==66567==    by 0x7DBED52: clone (clone.S:95)
==66567==
==66567== Invalid read of size 4
==66567==    at 0x412C5F: Kernel::KProcess::Finalize() (atomic_base.h:522)
==66567==    by 0x3C2BFB: Core::System::Impl::Shutdown() (kernel.cpp:96)
==66567==    by 0x2C2748: UnknownInlinedFun (core.cpp:457)
==66567==    by 0x2C2748: EmuThread::run() (bootmanager.cpp:117)
==66567==    by 0x7495340: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.2)
==66567==    by 0x6C8D44F: start_thread (pthread_create.c:473)
==66567==    by 0x7DBED52: clone (clone.S:95)
==66567==  Address 0x13dce958 is 27,864 bytes inside a block of size 28,184 free'd
==66567==    at 0x4845B0F: operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==66567==    by 0x48D7D9: Service::NVFlinger::NVFlinger::~NVFlinger() (unique_ptr.h:85)
==66567==    by 0x3C2727: Core::System::Impl::Shutdown() (unique_ptr.h:85)
==66567==    by 0x2C2748: UnknownInlinedFun (core.cpp:457)
==66567==    by 0x2C2748: EmuThread::run() (bootmanager.cpp:117)
==66567==    by 0x7495340: ??? (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.2)
==66567==    by 0x6C8D44F: start_thread (pthread_create.c:473)
==66567==    by 0x7DBED52: clone (clone.S:95)
==66567==  Block was alloc'd at
==66567==    at 0x4842FB3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==66567==    by 0x492C7B: Service::NVFlinger::NVFlinger::CreateLayerAtId(Service::VI::Display&, unsigned long) (unique_ptr.h:962)
==66567==    by 0x4931C0: Service::NVFlinger::NVFlinger::CreateLayer(unsigned long) (nvflinger.cpp:142)
==66567==    by 0x42D768: Service::AM::ISelfController::CreateManagedDisplayLayer(Kernel::HLERequestContext&) (am.cpp:472)
==66567==    by 0x4972DA: Service::ServiceFrameworkBase::HandleSyncRequest(Kernel::KServerSession&, Kernel::HLERequestContext&) (hle_ipc.cpp:212)
==66567==    by 0x4EA04B: Kernel::KServerSession::CompleteSyncRequest(Kernel::HLERequestContext&) (k_server_session.cpp:102)
==66567==    by 0x420328: std::_Function_handler<void (), Kernel::ServiceThread::Impl::QueueSyncRequest(Kernel::KSession&, std::shared_ptr<Kernel::HLERequestContext>&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) [clone .lto_priv.0] (service_thread.cpp:88)
==66567==    by 0x42E99D: std::thread::_State_impl<std::thread::_Invoker<std::tuple<Kernel::ServiceThread::Impl::Impl(Kernel::KernelCore&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}> > >::_M_run() (std_function.h:560)
==66567==    by 0x79FD693: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.29)
==66567==    by 0x6C8D44F: start_thread (pthread_create.c:473)
==66567==    by 0x7DBED52: clone (clone.S:95)
```

**Comment by v1993** [comment]
Can't reproduce on latest EA, can you please check as well, @german77? Seems fixed (or, at least, hidden for now) to me.

**Comment by v1993** [comment]
Actually, never mind, it's still happening. I've just switched over to tcmalloc and that hid the issue.

**Comment by bunnei** [comment]
@v1993 does this happen at all on mainline? I am trying to understand if this is actually related to #6551, but have not been able to reproduce the issue.

**Comment by v1993** [comment]
I'll check it out tomorrow. As I've explained in comment to that PR, it seems to be partially responsible for this, but not fully (however, I've only reverted that PR while testing, so other EA PRs were included). This is reproducible for me with build types Release/RelWithDebInfo, but not on Debug.

**Comment by bunnei** [comment]
Thanks. If it happens either way, it's possible that PR changes timing such that it is more common. However, based on the callstacks, it seems like a separate issue that we should tackle with a separate fix.

**Comment by bunnei** [comment]
Hey @v1993 -- ping again here if you could take a look, I am hoping to get #6551 merged today (unless it turns out that it is introducing new issues). Thank you!

**Comment by v1993** [comment]
Ah, thanks for reminding, will take a look ASAP.

**Comment by v1993** [comment]
Yeah, this also happens on mainline. Haven't checked that it's exactly the same crash, but it does segfault when stopping emulation.

**Comment by bunnei** [comment]
Thanks! I'll leave this open and keep investigating.

**Comment by A-w-x** [comment]
coming from #6931 

i cant get a log of that, the only thing gdb printed once was:

segfault in yuzu:Core_1
segfault in yuzu:Core_2
segfault in yuzu:EmuControl
no stack

thats it

on my device is 100% reproducible, i cannot stop the emulator

**Comment by hamelg** [comment]
Here, rebuilding yuzu with this flag has solved the issue : 
-DYUZU_USE_EXTERNAL_SDL2=OFF

**Comment by v1993** [comment]
Seems to be fixed in one of kernel rewrites - closing.
