### ISSUE TITLE
Vulkan LLVM segfault immediately for any rom

### ISSUE THREAD

**Issue by Beanow** [yuzu-emu/yuzu#7316]
- `yuzu-20211110-9a47a2fa6.AppImage`
- AMD Radeon RX 6800 XT (sienna_cichlid, LLVM 13.0.0, DRM 3.40, 5.11.0-40-generic) (0x73bf)
- Latest oibaf mesa

This happens for any rom when using Vulkan on llvmpipe, immediately when loading the rom.

```
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x0000555555a45445 in VideoCore::CreateGPU(Core::Frontend::EmuWindow&, Core::System&) ()
#2  0x0000555555754028 in Core::System::Impl::Init(Core::System&, Core::Frontend::EmuWindow&) ()
#3  0x00005555557552ea in Core::System::Impl::Load(Core::System&, Core::Frontend::EmuWindow&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long) ()
#4  0x000055555570bc82 in GMainWindow::LoadROM(QString const&, unsigned long, unsigned long) ()
#5  0x000055555570c530 in GMainWindow::BootGame(QString const&, unsigned long, unsigned long, StartGameType) ()
#6  0x00005555557180a2 in QtPrivate::QSlotObject<void (GMainWindow::*)(QString, unsigned long), QtPrivate::List<QString const&, unsigned long>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#7  0x00007ffff5b02b27 in  () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#8  0x00005555555d38d7 in GameList::GameChosen(QString const&, unsigned long) ()
#9  0x00005555556e2851 in GameList::ValidateEntry(QModelIndex const&) ()
#10 0x00007ffff5b02b27 in  () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#11 0x00007ffff790a3b5 in QAbstractItemView::activated(QModelIndex const&) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#12 0x00007ffff797eb87 in QTreeView::mouseDoubleClickEvent(QMouseEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#13 0x00007ffff76f240f in QWidget::event(QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#14 0x00007ffff779861e in QFrame::event(QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#15 0x00007ffff79163b3 in QAbstractItemView::viewportEvent(QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#16 0x00007ffff798055c in QTreeView::viewportEvent(QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#17 0x00007ffff5ac5190 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#18 0x00007ffff76b1312 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#19 0x00007ffff76b86c0 in QApplication::notify(QObject*, QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#20 0x00007ffff5ac5403 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#21 0x00007ffff76b76af in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#22 0x00007ffff770c2dc in  () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#23 0x00007ffff770f18d in  () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#24 0x00007ffff76b133c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#25 0x00007ffff76b8130 in QApplication::notify(QObject*, QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Widgets.so.5
#26 0x00007ffff5ac5403 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#27 0x00007ffff6195521 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Gui.so.5
#28 0x00007ffff6196b75 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Gui.so.5
#29 0x00007ffff616e9eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Gui.so.5
#30 0x00007fffee30d0fa in  () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5XcbQpa.so.5
#31 0x00007ffff42de17d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff42de400 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff42de4a3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007ffff5b27b9c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#35 0x00007ffff5ac3c8a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#36 0x00007ffff5acd487 in QCoreApplication::exec() () at /tmp/.mount_yuzu-2HHpd5R/usr/lib/libQt5Core.so.5
#37 0x00005555555be16b in main ()
```

**Comment by benderscruffy** [comment]
Please close
No update

**Comment by Beanow** [comment]
As commented here: couldn't reproduce anymore.
https://github.com/yuzu-emu/yuzu/issues/2559#issuecomment-1554257552
