### ISSUE TITLE
SDL_JOYSTICK_HIDAP=0 required with binary built on archlinux

### ISSUE THREAD

**Issue by hamelg** [yuzu-emu/yuzu#7517]
With pre-built binary yuzu-mainline, my controller is detected as "Microsoft Corp. Xbox360 Controller" and it works fine.
 
When rebuilding yuzu on a up to date archlinux system, my controller is wrongly detected as "Nintendo Co., Ltd. Pro Controller" and doesn't work. I see these dmesg errors in loop when yuzu is running.

```
input: Nintendo Co., Ltd. Pro Controller as /devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-2
usb 1-2.3: SerialNumber: 000000000001
usb 1-2.3: Manufacturer: Nintendo Co., Ltd.
usb 1-2.3: Product: Pro Controller
usb 1-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 1-2.3: New USB device found, idVendor=057e, idProduct=2009, bcdDevice= 2.00
usb 1-2.3: new full-speed USB device number 63 using xhci_hcd
usb 1-2.3: USB disconnect, device number 62
hid-generic 0003:057E:2009.00F3: input,hidraw8: USB HID v1.11 Joystick [Nintendo Co., Ltd. Pro Con
input: Nintendo Co., Ltd. Pro Controller as /devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-2
usb 1-2.3: SerialNumber: 000000000001
usb 1-2.3: Manufacturer: Nintendo Co., Ltd.
usb 1-2.3: Product: Pro Controller
usb 1-2.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 1-2.3: New USB device found, idVendor=057e, idProduct=2009, bcdDevice= 2.00
usb 1-2.3: new full-speed USB device number 62 using xhci_hcd
usb 1-2.3: USB disconnect, device number 61
...
```

and in the yuzu.log :

```
[  19.138725] Input <Error> input_common/drivers/sdl_driver.cpp:InitJoystick:287: Failed to open joystick 0
[  20.768269] Input <Error> input_common/drivers/sdl_driver.cpp:InitJoystick:287: Failed to open joystick
...
```

To fix this issue, I must use the environment variable SDL_JOYSTICK_HIDAPI=0.
See here : 
https://forum.endeavouros.com/t/sdl2-breakage-changes/10551

**Comment by german77** [comment]
idVendor=057e, idProduct=2009 this id is exactly the one of a pro controller. Could you try latest mainline. I updated SDL. I heard it has a few fixes for linux controllers

**Comment by hamelg** [comment]
Yes, yuzu-mainline-bin-0.842-1 has fixed the issue :)
I close the issue.

**Comment by hamelg** [comment]
Sorry, ignore my precedent message, I didn't compile it.
Built and tested again with the latest commit and the issue is still present.

**Comment by german77** [comment]
Have you done this?
![image](https://user-images.githubusercontent.com/5944268/145269904-5f4f20d8-6a50-4a92-bd6b-3c310d4c17ac.png)

**Comment by hamelg** [comment]
I tried your udev rule. It has no effect, so it's not a permission issue.

```
# ls -l /dev/hidraw*
crw-rw-r-- 1 root users 237, 0  8 déc.  20:34 /dev/hidraw0
crw-rw-r-- 1 root users 237, 1  8 déc.  20:34 /dev/hidraw1
crw-rw-r-- 1 root users 237, 2  8 déc.  20:34 /dev/hidraw2
crw-rw-r-- 1 root users 237, 3  8 déc.  20:34 /dev/hidraw3
crw-rw-r-- 1 root users 237, 4  8 déc.  20:34 /dev/hidraw4
crw-rw-r-- 1 root users 237, 5  8 déc.  20:34 /dev/hidraw5
crw-rw-r-- 1 root users 237, 6  8 déc.  20:34 /dev/hidraw6
crw-rw-r-- 1 root users 237, 7  8 déc.  20:34 /dev/hidraw7
crw-rw-r-- 1 root users 237, 8  8 déc.  20:34 /dev/hidraw8
```

**Comment by hamelg** [comment]
> idVendor=057e, idProduct=2009 this id is exactly the one of a pro controller. Could you try latest mainline. I updated SDL. I heard it has a few fixes for linux controllers

A soon as I run yuzu  without the flag SDL_JOYSTICK_HIDAP=0, linux doesn't see the same controller.

yuzu not running :
Bus 001 Device 056: ID 045e:028e Microsoft Corp. Xbox360 Controller

yuzu running :
Bus 001 Device 054: ID 057e:2009 Nintendo Co., Ltd Switch Pro Controller
The "Device 0xx"  is incrementing quickly.

**Comment by german77** [comment]
Not sure what could be the issue. HIDAPI is used to detect Nintendo controllers and have rumble working on DS4/5 controller. Disabling HIDAPI just means there is zero support for nintendo controllers. Hence why it's detected as xinput since 8bitDo can emulate multiple controller types

**Comment by spholz** [comment]
I seem to get the same issue.
It seems like the OpenJoystick function for the pro controller `HIDAPI_DriverSwitch_OpenJoystick` fails at the call `BReadDeviceInfo`. `BReadDeviceInfo` calls `WritePropietary` which then calls `WritePacket`.
`WriteOutput` seems to use the rumble thread (?). It then tries to create a mutex but fails because SDL_THREADS_DISABLED is set (set by default in CMakeLists.txt).
If I set SDL_THREADS:BOOL to ON everything seems to be fine.

**Comment by spholz** [comment]
gdb backtrace for reference:
```
#0  SDL_CreateMutex_REAL () at /media/repos/yuzu/externals/SDL/src/thread/generic/SDL_sysmutex.c:47
#1  0x0000555556491931 in SDL_HIDAPI_StartRumbleThread (ctx=0x555557d886a0 <rumble_context>) at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_rumble.c:140
#2  0x0000555556491a30 in SDL_HIDAPI_LockRumble () at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_rumble.c:166
#3  0x00005555564928fd in WriteOutput (ctx=0x555558568ee0, data=0x7fffffffc730 "\200\001", size=64) at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:358
#4  0x0000555556492bc8 in WritePacket (ctx=0x555558568ee0, pBuf=0x7fffffffc730, ucLen=64 '@') at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:444
#5  0x0000555556492d68 in WriteProprietary (ctx=0x555558568ee0, ucCommand=k_eSwitchProprietaryCommandIDs_Status, pBuf=0x0, ucLen=0 '\000', waitForReply=SDL_TRUE) at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:487
#6  0x0000555556493084 in BReadDeviceInfo (ctx=0x555558568ee0) at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:606
#7  0x0000555556493e37 in HIDAPI_DriverSwitch_OpenJoystick (device=0x55555847e930, joystick=0x555558508eb0) at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapi_switch.c:874
#8  0x00005555563de8a1 in HIDAPI_JoystickOpen (joystick=0x555558508eb0, device_index=0) at /media/repos/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:851
#9  0x00005555563bb7b0 in SDL_JoystickOpen_REAL (device_index=0) at /media/repos/yuzu/externals/SDL/src/joystick/SDL_joystick.c:425
#10 0x000055555627ed02 in SDL_JoystickOpen (a=0) at /media/repos/yuzu/externals/SDL/src/dynapi/SDL_dynapi_procs.h:228
#11 0x0000555555fc16c7 in InputCommon::SDLDriver::InitJoystick(int) (this=0x555557f6d160, joystick_index=0) at /media/repos/yuzu/src/input_common/drivers/sdl_driver.cpp:279
...
```
mutex->sem is null because SDL_CreateSemaphore fails
