### ISSUE TITLE
New Super Mario Bros. U Deluxe keeps crashing in MapView

### ISSUE THREAD

**Issue by delphir-com** [yuzu-emu/yuzu#7738]
New Super Mario Bros. U Deluxe keeps crashing in MapView when positioned over the "water" area (the one from the screenshot) in mapview mode.

![image](https://user-images.githubusercontent.com/7754573/149957382-656e4fad-c697-41c5-a9d0-bb1e9ad7a0b6.png)

How to reproduce:
0. set OpenGL (Vulcan can start the game but it randomly crashes during gameplay in a few minutes)
1. start the game
2. select number of players (2 in my case)
3. hit L to switch to the Map View
4. use navigation joystick to position the map like it is seen on the screenshot and leave it for a while. 

usually yuzu crashes within 10-15s, but I had to wait about 1.5 minutes once.
the issue can be easily reproduced.

other than that - OpenGL works pretty fine anywhere else during the game on `yuzu-20220105-43771282a.AppImage` but randomly crashes during the game on `yuzu-20220111`, `yuzu-20220112`, `yuzu-20220113`, `yuzu-20220116`.

this is how the console looks like with debug enabled:

```
[  52.239303] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  52.239426] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  52.239546] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  52.239664] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  52.239799] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  52.240118] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  52.240368] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.667639] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.669553] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.669671] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.685590] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.689262] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.693658] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.699240] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.700115] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  58.700620] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  61.833988] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  61.834266] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.000898] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.001326] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.333832] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.334137] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.667147] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.667442] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.983959] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  64.984279] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  67.567378] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_ctrl.cpp:IocCtrlClearEventWait:209: cleared event wait on, event_id: 0
[  68.809404] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  68.809673] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  69.368486] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  69.368806] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  69.692928] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  69.693154] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  70.026272] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  70.026593] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  71.959731] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  71.959977] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  74.043349] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  74.043583] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  74.376513] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  74.376772] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  74.742423] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_ctrl.cpp:IocCtrlClearEventWait:209: cleared event wait on, event_id: 0
[  75.371775] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  75.372036] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  75.770813] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  75.771061] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvmap.cpp:IocFree:247: (STUBBED) called
[  77.345577] Service.NVDRV <Warning> core/hle/service/nvdrv/devices/nvhost_ctrl.cpp:IocCtrlClearEventWait:209: cleared event wait on, event_id: 0
Aborted (core dumped)
```

OS: Linux, Ubuntu 20.04
Linux KUBUNTU 5.13.0-25-generic #26~20.04.1-Ubuntu SMP Fri Jan 7 16:27:40 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CPU: i5-8600K (internal gpu)
Ram: 32GB

**Comment by v1993** [comment]
Would you mind running under GDB and finding the exact point of failure? If you're unsure about how to do that (or get stuck with sigsegv on game launch in debugger), please ask in yuzu discord for help.

**Comment by G-Spawn** [comment]
If you're able to provide a save file for the game I'd love to poke at it. Can right click game open save location and zip and add to post.

**Comment by delphir-com** [comment]
@G-Spawn here is the attached save-file
[mario.zip](https://github.com/yuzu-emu/yuzu/files/7891411/mario.zip)

**Comment by delphir-com** [comment]
@v1993 

here is the output from GDB at the moment of crash when running `yuzu-20220112-a482e353f.AppImage`:

```
Thread 35 "yuzu:gl0" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f7e5dffd700 (LWP 33241)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) 
Continuing.
Couldn't get registers: No such process.
(gdb) [Thread 0x7fffda26c700 (LWP 33500) exited]
[Thread 0x7fffd926a700 (LWP 33498) exited]
[Thread 0x7fffd9a6b700 (LWP 33497) exited]
[Thread 0x7f7d6de40700 (LWP 33479) exited]
[Thread 0x7f7d6e641700 (LWP 33478) exited]
[Thread 0x7f7d6ee42700 (LWP 33477) exited]
[Thread 0x7f7d6f643700 (LWP 33476) exited]
[Thread 0x7f7d6fe44700 (LWP 33472) exited]
[Thread 0x7f7d70645700 (LWP 33468) exited]
[Thread 0x7f7d70e46700 (LWP 33467) exited]
[Thread 0x7f7d71647700 (LWP 33466) exited]
[Thread 0x7f7d71e48700 (LWP 33465) exited]
[Thread 0x7f7d72649700 (LWP 33464) exited]
[Thread 0x7f7d7464b700 (LWP 33463) exited]
[Thread 0x7f7d74e4c700 (LWP 33457) exited]
[Thread 0x7f7d7564d700 (LWP 33456) exited]
[Thread 0x7f7d75e4e700 (LWP 33455) exited]
[Thread 0x7f7d7664f700 (LWP 33454) exited]
[Thread 0x7f7d76e50700 (LWP 33453) exited]
[Thread 0x7f7d77651700 (LWP 33452) exited]
[Thread 0x7f7d77e52700 (LWP 33451) exited]
[Thread 0x7f7d78653700 (LWP 33450) exited]
[Thread 0x7f7d78e54700 (LWP 33449) exited]
[Thread 0x7f7d79655700 (LWP 33448) exited]
[Thread 0x7f7d79e56700 (LWP 33447) exited]
[Thread 0x7f7d7a657700 (LWP 33446) exited]
[Thread 0x7f7d7ae58700 (LWP 33445) exited]
[Thread 0x7f7d7b659700 (LWP 33443) exited]
[Thread 0x7f7d7be5a700 (LWP 33442) exited]
[Thread 0x7f7d7c65b700 (LWP 33441) exited]
[Thread 0x7f7d7de5c700 (LWP 33440) exited]
[Thread 0x7f7d7e65d700 (LWP 33439) exited]
[Thread 0x7f7d7ee5e700 (LWP 33438) exited]
[Thread 0x7f7d7f65f700 (LWP 33437) exited]
[Thread 0x7f7d7fe60700 (LWP 33436) exited]
[Thread 0x7f7d80661700 (LWP 33435) exited]
[Thread 0x7f7d80e62700 (LWP 33434) exited]
[Thread 0x7f7d81663700 (LWP 33433) exited]
[Thread 0x7f7d81e64700 (LWP 33432) exited]
[Thread 0x7f7d82665700 (LWP 33431) exited]
[Thread 0x7f7d82e66700 (LWP 33430) exited]
[Thread 0x7f7d83667700 (LWP 33429) exited]
[Thread 0x7f7d83e68700 (LWP 33428) exited]
[Thread 0x7f7d84669700 (LWP 33427) exited]
[Thread 0x7f7d84e6a700 (LWP 33426) exited]
[Thread 0x7f7d8566b700 (LWP 33425) exited]
[Thread 0x7f7d85e6c700 (LWP 33424) exited]
[Thread 0x7f7d8666d700 (LWP 33423) exited]
[Thread 0x7f7d86e6e700 (LWP 33422) exited]
[Thread 0x7f7d8766f700 (LWP 33421) exited]
[Thread 0x7f7d87e70700 (LWP 33420) exited]
[Thread 0x7f7d88671700 (LWP 33419) exited]
[Thread 0x7f7d88e72700 (LWP 33418) exited]
[Thread 0x7f7d89673700 (LWP 33417) exited]
[Thread 0x7f7d89e74700 (LWP 33416) exited]
[Thread 0x7f7d8a675700 (LWP 33415) exited]
[Thread 0x7f7d8ae76700 (LWP 33414) exited]
[Thread 0x7f7d8b677700 (LWP 33413) exited]
[Thread 0x7f7d8be78700 (LWP 33412) exited]
[Thread 0x7f7d8c679700 (LWP 33411) exited]
[Thread 0x7f7d8ce7a700 (LWP 33410) exited]
[Thread 0x7f7d8d67b700 (LWP 33409) exited]
[Thread 0x7f7d8de7c700 (LWP 33408) exited]
[Thread 0x7f7d8e67d700 (LWP 33407) exited]
[Thread 0x7f7d8ee7e700 (LWP 33406) exited]
[Thread 0x7f7d8f67f700 (LWP 33405) exited]
[Thread 0x7f7d8fe80700 (LWP 33404) exited]
[Thread 0x7f7d90681700 (LWP 33403) exited]
[Thread 0x7f7d90e82700 (LWP 33402) exited]
[Thread 0x7f7d91683700 (LWP 33401) exited]
[Thread 0x7f7d91e84700 (LWP 33400) exited]
[Thread 0x7f7d92685700 (LWP 33399) exited]
[Thread 0x7f7d92e86700 (LWP 33398) exited]
[Thread 0x7f7d93687700 (LWP 33397) exited]
[Thread 0x7f7d93e88700 (LWP 33396) exited]
[Thread 0x7f7d94689700 (LWP 33395) exited]
[Thread 0x7f7d94e8a700 (LWP 33394) exited]
[Thread 0x7f7d9568b700 (LWP 33393) exited]
[Thread 0x7f7d95e8c700 (LWP 33392) exited]
[Thread 0x7f7d9668d700 (LWP 33391) exited]
[Thread 0x7f7d96e8e700 (LWP 33390) exited]
[Thread 0x7f7d9768f700 (LWP 33389) exited]
[Thread 0x7f7d97e90700 (LWP 33388) exited]
[Thread 0x7f7d98691700 (LWP 33387) exited]
[Thread 0x7f7d98e92700 (LWP 33386) exited]
[Thread 0x7f7d99693700 (LWP 33385) exited]
[Thread 0x7f7d99e94700 (LWP 33384) exited]
[Thread 0x7f7d9a695700 (LWP 33383) exited]
[Thread 0x7f7d9ae96700 (LWP 33382) exited]
[Thread 0x7f7d9b697700 (LWP 33381) exited]
[Thread 0x7f7d9be98700 (LWP 33380) exited]
[Thread 0x7f7d9c699700 (LWP 33379) exited]
[Thread 0x7f7d9df9b700 (LWP 33378) exited]
[Thread 0x7f7d9e79c700 (LWP 33377) exited]
[Thread 0x7f7d9ef9d700 (LWP 33376) exited]
[Thread 0x7f7d9f79e700 (LWP 33375) exited]
[Thread 0x7f7d9ff9f700 (LWP 33374) exited]
[Thread 0x7f7da07a0700 (LWP 33373) exited]
[Thread 0x7f7da0fa1700 (LWP 33372) exited]
[Thread 0x7f7da17a2700 (LWP 33371) exited]
[Thread 0x7f7da1fa3700 (LWP 33370) exited]
[Thread 0x7f7da27a4700 (LWP 33369) exited]
[Thread 0x7f7da2fa5700 (LWP 33368) exited]
[Thread 0x7f7da37a6700 (LWP 33367) exited]
[Thread 0x7f7da3fa7700 (LWP 33366) exited]
[Thread 0x7f7da47a8700 (LWP 33365) exited]
[Thread 0x7f7da4fa9700 (LWP 33364) exited]
[Thread 0x7f7da57aa700 (LWP 33363) exited]
[Thread 0x7f7da5fab700 (LWP 33362) exited]
[Thread 0x7f7da67ac700 (LWP 33361) exited]
[Thread 0x7f7da6fad700 (LWP 33360) exited]
[Thread 0x7f7da77ae700 (LWP 33359) exited]
[Thread 0x7f7da7faf700 (LWP 33358) exited]
[Thread 0x7f7da87b0700 (LWP 33357) exited]
[Thread 0x7f7da8fb1700 (LWP 33356) exited]
[Thread 0x7f7da97b2700 (LWP 33355) exited]
[Thread 0x7f7da9fb3700 (LWP 33354) exited]
[Thread 0x7f7daa7b4700 (LWP 33353) exited]
[Thread 0x7f7daafb5700 (LWP 33352) exited]
[Thread 0x7f7dab7b6700 (LWP 33351) exited]
[Thread 0x7f7dabfb7700 (LWP 33350) exited]
[Thread 0x7f7dac7b8700 (LWP 33349) exited]
[Thread 0x7f7dacfb9700 (LWP 33348) exited]
[Thread 0x7f7dad7ba700 (LWP 33347) exited]
[Thread 0x7f7dadfbb700 (LWP 33346) exited]
[Thread 0x7f7dae7bc700 (LWP 33345) exited]
[Thread 0x7f7daefbd700 (LWP 33344) exited]
[Thread 0x7f7daf7be700 (LWP 33343) exited]
[Thread 0x7f7daffbf700 (LWP 33342) exited]
[Thread 0x7f7db07c0700 (LWP 33341) exited]
[Thread 0x7f7db0fc1700 (LWP 33340) exited]
[Thread 0x7f7db17c2700 (LWP 33339) exited]
[Thread 0x7f7db1fc3700 (LWP 33338) exited]
[Thread 0x7f7db27c4700 (LWP 33337) exited]
[Thread 0x7f7db2fc5700 (LWP 33336) exited]
[Thread 0x7f7db37c6700 (LWP 33335) exited]
[Thread 0x7f7db3fc7700 (LWP 33334) exited]
[Thread 0x7f7db47c8700 (LWP 33333) exited]
[Thread 0x7f7db4fc9700 (LWP 33332) exited]
[Thread 0x7f7db57ca700 (LWP 33331) exited]
[Thread 0x7f7db5fcb700 (LWP 33330) exited]
[Thread 0x7f7db67cc700 (LWP 33329) exited]
[Thread 0x7f7db6fcd700 (LWP 33328) exited]
[Thread 0x7f7db77ce700 (LWP 33327) exited]
[Thread 0x7f7db7fcf700 (LWP 33326) exited]
[Thread 0x7f7db87d0700 (LWP 33325) exited]
[Thread 0x7f7db8fd1700 (LWP 33324) exited]
[Thread 0x7f7db97d2700 (LWP 33323) exited]
[Thread 0x7f7db9fd3700 (LWP 33322) exited]
[Thread 0x7f7dba7d4700 (LWP 33321) exited]
[Thread 0x7f7dbafd5700 (LWP 33320) exited]
[Thread 0x7f7dbb7d6700 (LWP 33319) exited]
[Thread 0x7f7dbbfd7700 (LWP 33318) exited]
[Thread 0x7f7dbc7d8700 (LWP 33317) exited]
[Thread 0x7f7dbcfd9700 (LWP 33316) exited]
[Thread 0x7f7dbd7da700 (LWP 33315) exited]
[Thread 0x7f7dbdfdb700 (LWP 33314) exited]
[Thread 0x7f7dbe7dc700 (LWP 33313) exited]
[Thread 0x7f7dbefdd700 (LWP 33312) exited]
[Thread 0x7f7dbf7de700 (LWP 33311) exited]
[Thread 0x7f7dbffdf700 (LWP 33310) exited]
[Thread 0x7f7dc07e0700 (LWP 33309) exited]
[Thread 0x7f7dc0fe1700 (LWP 33308) exited]
[Thread 0x7f7dc17e2700 (LWP 33307) exited]
[Thread 0x7f7dc1fe3700 (LWP 33306) exited]
[Thread 0x7f7dc27e4700 (LWP 33305) exited]
[Thread 0x7f7dc2fe5700 (LWP 33304) exited]
[Thread 0x7f7dc37e6700 (LWP 33303) exited]
[Thread 0x7f7dc3fe7700 (LWP 33302) exited]
[Thread 0x7f7dc47e8700 (LWP 33301) exited]
[Thread 0x7f7dc4fe9700 (LWP 33300) exited]
[Thread 0x7f7dc57ea700 (LWP 33299) exited]
[Thread 0x7f7dc5feb700 (LWP 33298) exited]
[Thread 0x7f7dc67ec700 (LWP 33297) exited]
[Thread 0x7f7dc6fed700 (LWP 33296) exited]
[Thread 0x7f7dc77ee700 (LWP 33295) exited]
[Thread 0x7f7dc7fef700 (LWP 33294) exited]
[Thread 0x7f7dc87f0700 (LWP 33293) exited]
[Thread 0x7f7dc8ff1700 (LWP 33292) exited]
[Thread 0x7f7dc97f2700 (LWP 33291) exited]
[Thread 0x7f7dc9ff3700 (LWP 33290) exited]
[Thread 0x7f7dca7f4700 (LWP 33289) exited]
[Thread 0x7f7dcaff5700 (LWP 33288) exited]
[Thread 0x7f7dcb7f6700 (LWP 33287) exited]
[Thread 0x7f7dcbff7700 (LWP 33286) exited]
[Thread 0x7f7dcc7f8700 (LWP 33285) exited]
[Thread 0x7f7dccff9700 (LWP 33284) exited]
[Thread 0x7f7dcd7fa700 (LWP 33283) exited]
[Thread 0x7f7dcdffb700 (LWP 33282) exited]
[Thread 0x7f7dce7fc700 (LWP 33281) exited]
[Thread 0x7f7dceffd700 (LWP 33280) exited]
[Thread 0x7f7dcf7fe700 (LWP 33279) exited]
[Thread 0x7f7dcffff700 (LWP 33278) exited]
[Thread 0x7f7dd4ff9700 (LWP 33277) exited]
[Thread 0x7f7dd57fa700 (LWP 33276) exited]
[Thread 0x7f7dd5ffb700 (LWP 33275) exited]
[Thread 0x7f7dd67fc700 (LWP 33274) exited]
[Thread 0x7f7dd6ffd700 (LWP 33273) exited]
[Thread 0x7f7dd77fe700 (LWP 33272) exited]
[Thread 0x7f7dd7fff700 (LWP 33271) exited]
[Thread 0x7f7de4f3c700 (LWP 33270) exited]
[Thread 0x7f7de573d700 (LWP 33269) exited]
[Thread 0x7f7de5f3e700 (LWP 33268) exited]
[Thread 0x7f7decf3c700 (LWP 33267) exited]
[Thread 0x7f7ded73d700 (LWP 33266) exited]
[Thread 0x7f7dedf3e700 (LWP 33265) exited]
[Thread 0x7f7df4f3c700 (LWP 33264) exited]
[Thread 0x7f7df573d700 (LWP 33263) exited]
[Thread 0x7f7df5f3e700 (LWP 33262) exited]
[Thread 0x7f7e00f3c700 (LWP 33261) exited]
[Thread 0x7f7e0173d700 (LWP 33260) exited]
[Thread 0x7f7e01f3e700 (LWP 33259) exited]
[Thread 0x7f7e10f3c700 (LWP 33258) exited]
[Thread 0x7f7e1173d700 (LWP 33257) exited]
[Thread 0x7f7e11f3e700 (LWP 33256) exited]
[Thread 0x7f7e18ffa700 (LWP 33255) exited]
[Thread 0x7f7e197fb700 (LWP 33254) exited]
[Thread 0x7f7e19ffc700 (LWP 33253) exited]
[Thread 0x7f7e1b7fe700 (LWP 33252) exited]
[Thread 0x7f7e1bfff700 (LWP 33251) exited]
[Thread 0x7f7e38f33700 (LWP 33250) exited]
[Thread 0x7f7e39734700 (LWP 33249) exited]
[Thread 0x7f7e39f35700 (LWP 33248) exited]
[Thread 0x7f7e3a736700 (LWP 33247) exited]
[Thread 0x7f7e3af37700 (LWP 33246) exited]
[Thread 0x7f7e3b738700 (LWP 33245) exited]
[Thread 0x7f7e3bf39700 (LWP 33244) exited]
[Thread 0x7f7e5cffb700 (LWP 33243) exited]
[Thread 0x7f7e5d7fc700 (LWP 33242) exited]
[Thread 0x7f7e731fe700 (LWP 33240) exited]
[Thread 0x7f7e739ff700 (LWP 33239) exited]
[Thread 0x7fff849fa700 (LWP 33238) exited]
[Thread 0x7fff851fb700 (LWP 33237) exited]
[Thread 0x7fff86ffd700 (LWP 33236) exited]
[Thread 0x7fff877fe700 (LWP 33234) exited]
[Thread 0x7fff87fff700 (LWP 33233) exited]
[Thread 0x7fffac845700 (LWP 33232) exited]
[Thread 0x7fffad046700 (LWP 33228) exited]
[Thread 0x7fffad847700 (LWP 33227) exited]
[Thread 0x7fffae048700 (LWP 33226) exited]
[Thread 0x7fffae849700 (LWP 33225) exited]
[Thread 0x7fffb8ee9700 (LWP 33224) exited]
[Thread 0x7fffb96ea700 (LWP 33223) exited]
[Thread 0x7fffb9eeb700 (LWP 33222) exited]
[Thread 0x7fffba6ec700 (LWP 33221) exited]
[Thread 0x7fffc17fa700 (LWP 33218) exited]
[Thread 0x7fffc1ffb700 (LWP 33217) exited]
[Thread 0x7fffc27fc700 (LWP 33216) exited]
[Thread 0x7fffc2ffd700 (LWP 33215) exited]
[Thread 0x7fffc37fe700 (LWP 33214) exited]
[Thread 0x7fffc3fff700 (LWP 33213) exited]
[Thread 0x7fffdbdda700 (LWP 33193) exited]
[Thread 0x7fffe8c42700 (LWP 33192) exited]
[Thread 0x7fffe9443700 (LWP 33191) exited]
[Thread 0x7fffeb954700 (LWP 33190) exited]
[Thread 0x7ffff0c55880 (LWP 33168) exited]
--Type <RET> for more, q to quit, c to continue without paging--

```

**Comment by delphir-com** [comment]
just in case, the same test with `yuzu-20220117-c5647b8c0.AppImage`

```
Thread 36 "yuzu:gl0" received signal SIGABRT, Aborted.
[Switching to Thread 0x7f7de1e7d700 (LWP 33888)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
```

and a lot of registers/exited-thread messages after this (~similar to the ones from prev example)

**Comment by v1993** [comment]
You should print backtrace (`bt`) after the first abort message. It's not quite useful otherwise.

**Comment by delphir-com** [comment]
```
Thread 237 "yuzu:GPU" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff853cc700 (LWP 66767)]
__GI_raise (sig=sig@entry=6) at /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:50
50	/build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5056859 in __GI_abort () at /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79
#2  0x00007fffba81e0d3 in  () at /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#3  0x00007fffbb491f0e in  () at /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#4  0x00007fffba8889ad in  () at /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#5  0x00007fffba82ec3f in  () at /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
#6  0x00007fffc83a3e27 in glPrimitiveBoundingBox () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#7  0x00007fffc8396965 in  () at /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#8  0x00007fffc85edde2 in  () at /tmp/.mount_yuzu-2msST6k/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#9  0x00007ffff619043f in QOpenGLContext::swapBuffers(QSurface*) () at /tmp/.mount_yuzu-2msST6k/usr/lib/libQt5Gui.so.5
#10 0x0000555555ad40d2 in OpenGL::RendererOpenGL::SwapBuffers(Tegra::FramebufferConfig const*) ()
#11 0x0000555555aa8f4f in VideoCommon::GPUThread::RunThread(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::DmaPusher&, VideoCommon::GPUThread::SynchState&) ()
#12 0x0000555555aa9752 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::stop_token, Core::System&, VideoCore::RendererBase&, Core::Frontend::GraphicsContext&, Tegra::DmaPusher&, VideoCommon::GPUThread::SynchState&), std::stop_token, std::reference_wrapper<Core::System>, std::reference_wrapper<VideoCore::RendererBase>, std::reference_wrapper<Core::Frontend::GraphicsContext>, std::reference_wrapper<Tegra::DmaPusher>, std::reference_wrapper<VideoCommon::GPUThread::SynchState> > > >::_M_run() ()
#13 0x00007ffff54614c0 in  () at /tmp/.mount_yuzu-2msST6k/usr/optional/libstdc++/libstdc++.so.6
#14 0x00007ffff57a3609 in start_thread (arg=<optimized out>) at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
#15 0x00007ffff5153293 in clone () at /build/glibc-eX1tMB/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:9
```

**Comment by delphir-com** [comment]
@v1993 @G-Spawn do you need any extra info regarding this issue?

**Comment by G-Spawn** [comment]
Sorry for the delay. I couldn't seem to replicate your issue at least on my rigs. It may need more looking into by the devs.

**Comment by Morigaz** [comment]
Don't Open the map :D

**Comment by G-Spawn** [comment]
> Don't Open the map :D

Please dont reply in future if you're only planning on joking around.
