### ISSUE TITLE
[1093-1094] Crash on startup when controller connected (Flatpak)

### ISSUE THREAD

**Issue by Beanow** [yuzu-emu/yuzu#8606]
Running on Steam Deck, when I have an Xbox 360 controller connected, Yuzu crashes on startup.
I've not had this issue with 1085.

Here a stacktrace

```
Reading symbols from /app/bin/yuzu...
Reading symbols from /usr/lib/debug//app/bin/yuzu.debug...
(gdb) r
Starting program: /app/bin/yuzu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe5e42640 (LWP 17)]
[New Thread 0x7fffdffbe640 (LWP 18)]
[New Thread 0x7fffddaed640 (LWP 19)]
[New Thread 0x7fffdd1ab640 (LWP 20)]
[New Thread 0x7fffdc9aa640 (LWP 21)]
[New Thread 0x7fffcffff640 (LWP 22)]
[New Thread 0x7fffcf7fe640 (LWP 23)]
[New Thread 0x7fffceffd640 (LWP 24)]
[New Thread 0x7fffce7fc640 (LWP 25)]
[New Thread 0x7fffcdffb640 (LWP 26)]
[New Thread 0x7fffcd7fa640 (LWP 27)]
[New Thread 0x7fffccff9640 (LWP 28)]
[New Thread 0x7fffa3fff640 (LWP 29)]
[New Thread 0x7fffa37fe640 (LWP 30)]
[New Thread 0x7fffa2ffd640 (LWP 31)]
[New Thread 0x7fffa27fc640 (LWP 32)]
[New Thread 0x7fffa15eb640 (LWP 33)]
[New Thread 0x7fffa0dea640 (LWP 34)]
[New Thread 0x7fff93fff640 (LWP 35)]
[New Thread 0x7fff937fe640 (LWP 36)]
[New Thread 0x7fff92ffd640 (LWP 37)]
[New Thread 0x7fff927fc640 (LWP 38)]
[New Thread 0x7fff91ffb640 (LWP 39)]
[New Thread 0x7fff917fa640 (LWP 40)]
[New Thread 0x7fff90ff9640 (LWP 41)]
[New Thread 0x7fff7bfff640 (LWP 42)]

Thread 1 "yuzu" received signal SIGSEGV, Segmentation fault.
0x00007fffee51ead1 in __strncmp_avx2 () from /usr/lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fffee51ead1 in __strncmp_avx2 () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x0000555555db9ae4 in SDL_CreateJoystickName
    (vendor=<optimized out>, product=<optimized out>, vendor_name=vendor_name@entry=0x0, product_name=product_name@entry=0x0)
    at /run/build/yuzu/externals/SDL/src/joystick/SDL_joystick.c:1814
#2  0x0000555555e089f0 in HIDAPI_AddDevice (info=<optimized out>) at /run/build/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:544
#3  HIDAPI_UpdateDeviceList () at /run/build/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:640
#4  0x0000555555e08e94 in HIDAPI_JoystickDetect () at /run/build/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:786
#5  HIDAPI_JoystickDetect () at /run/build/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:781
#6  HIDAPI_JoystickInit () at /run/build/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:400
#7  HIDAPI_JoystickInit () at /run/build/yuzu/externals/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:360
#8  0x0000555555db789e in SDL_JoystickInit () at /run/build/yuzu/externals/SDL/src/joystick/SDL_joystick.c:247
#9  0x0000555555e0e0f5 in SDL_InitSubSystem_REAL (flags=25088) at /run/build/yuzu/externals/SDL/src/SDL.c:283
#10 0x0000555555aa44d0 in InputCommon::SDLDriver::SDLDriver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    (input_engine_="", this=0x55555736d0f0) at /run/build/yuzu/src/input_common/drivers/sdl_driver.cpp:427
#11 std::construct_at<InputCommon::SDLDriver, char const (&) [4]>(InputCommon::SDLDriver*, char const (&) [4]) (__location=0x55555736d0f0)
    at /usr/include/c++/11.3.0/bits/stl_construct.h:97
#12 std::allocator_traits<std::allocator<InputCommon::SDLDriver> >::construct<InputCommon::SDLDriver, char const (&) [4]>(std::allocator<InputCommon::SDLDriver>&, InputCommon::SDLDriver*, char const (&) [4]) (__p=0x55555736d0f0, __a=<optimized out>) at /usr/include/c++/11.3.0/bits/alloc_traits.h:518
#13 std::_Sp_counted_ptr_inplace<InputCommon::SDLDriver, std::allocator<InputCommon::SDLDriver>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<char const (&) [4]>(std::allocator<InputCommon::SDLDriver>, char const (&) [4]) (__a=..., this=0x55555736d0e0)
    at /usr/include/c++/11.3.0/bits/shared_ptr_base.h:519
#14 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<InputCommon::SDLDriver, std::allocator<InputCommon::SDLDriver>, char const (&) [4]>(InputCommon::SDLDriver*&, std::_Sp_alloc_shared_tag<std::allocator<InputCommon::SDLDriver> >, char const (&) [4])
    (__a=..., __p=<optimized out>, this=<optimized out>) at /usr/include/c++/11.3.0/bits/shared_ptr_base.h:650
#15 std::__shared_ptr<InputCommon::SDLDriver, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<InputCommon::SDLDriver>, char const (&) [4]>(std::_Sp_alloc_shared_tag<std::allocator<InputCommon::SDLDriver> >, char const (&) [4]) (__tag=..., this=<optimized out>)
    at /usr/include/c++/11.3.0/bits/shared_ptr_base.h:1342
#16 std::shared_ptr<InputCommon::SDLDriver>::shared_ptr<std::allocator<InputCommon::SDLDriver>, char const (&) [4]>(std::_Sp_alloc_shared_tag<std::allocator<InputCommon::SDLDriver> >, char const (&) [4]) (__tag=..., this=<optimized out>) at /usr/include/c++/11.3.0/bits/shared_ptr.h:409
#17 std::allocate_shared<InputCommon::SDLDriver, std::allocator<InputCommon::SDLDriver>, char const (&) [4]>(std::allocator<InputCommon::SDLDriver> const&, char const (&) [4]) (__a=<optimized out>) at /usr/include/c++/11.3.0/bits/shared_ptr.h:863
#18 std::make_shared<InputCommon::SDLDriver, char const (&) [4]>(char const (&) [4]) () at /usr/include/c++/11.3.0/bits/shared_ptr.h:879
#19 InputCommon::InputSubsystem::Impl::Initialize() (this=0x55555719bbd0) at /run/build/yuzu/src/input_common/main.cpp:82
#20 0x00005555558051f8 in InputCommon::InputSubsystem::Initialize() (this=<optimized out>) at /run/build/yuzu/src/input_common/main.cpp:346
#21 GRenderWindow::GRenderWindow(GMainWindow*, EmuThread*, std::shared_ptr<InputCommon::InputSubsystem>, Core::System&)
   Python Exception <class 'gdb.error'>: value has been optimized out
 (system_=<optimized out>, input_subsystem_=, emu_thread_=<optimized out>, parent=0x7fffffffd840, this=0x555557373990)
--Type <RET> for more, q to quit, c to continue without paging--c
    at /run/build/yuzu/src/yuzu/bootmanager.cpp:304
#22 GMainWindow::InitializeWidgets() (this=0x7fffffffd840) at /run/build/yuzu/src/yuzu/main.cpp:806
#23 0x00005555556ef7ec in GMainWindow::GMainWindow() (this=0x7fffffffd840) at /run/build/yuzu/src/yuzu/main.cpp:276
#24 main(int, char**) (argc=<optimized out>, argv=<optimized out>) at /run/build/yuzu/src/yuzu/main.cpp:3895
(gdb) 
```

**Comment by lat9nq** [comment]
Caused by #8525

**Comment by Beanow** [comment]
Updated to 1099 flatpak, and the issue doesn't occur.
I think that confirms #8607 fixed the problem.
