### ISSUE TITLE
Yuzu 2888 Crash in Xenoblade 3 Pentelas Region - Vulkan

### ISSUE THREAD

**Issue by DreadwyrmBahamut** [yuzu-emu/yuzu#8714]
I have tested this multiple times with just about every setting with me and about 4 confirmed other people all crashing in the same place in the caves of beginning of pentelas region in xbc3, i think it might be due to the water effects? not sure. OpenGL doesnt cause a crash only Vulkan

**Comment by german77** [comment]
Please provide a log and a save file

**Comment by DreadwyrmBahamut** [comment]
> Please provide a log and a save file

I can provide a save file for sure, but not sure how to get a log, I should of added this issue is on steamdeck vulkan, not PC, works fine on PC (for me at least as of now)

Also how do i provide these things? is there an upload site you guys prefer?

**Comment by goldenx86** [comment]
You should be able to upload zips here without issue.
For the log file, here: https://yuzu-emu.org/help/reference/log-files/

**Comment by DreadwyrmBahamut** [comment]
Yeah tried zipping my saves in a folder and dragging and dropping in here and it says "we dont support that file type" >_<

**Comment by DreadwyrmBahamut** [comment]
best i can do 
https://mega.nz/folder/dPEB2R5T#dEWgJmwSXacWBfHDUhZcLQ

**Comment by Bjorn29512** [comment]
are you using resmod by any chance ? try again without the mod and deleting your vulkan pipeline cache

**Comment by DreadwyrmBahamut** [comment]
> 

Ok let me try that when I get home

**Comment by DreadwyrmBahamut** [comment]
Is the pipeline cache in shaders - >GID -> Vulkan.bin ?

**Comment by DreadwyrmBahamut** [comment]
I deleted the Vulkan.bin and removed ResMod, still crashing, to be precise what it does is freezes, the screen will go black and then come back, and freeze indeffinitely

**Comment by Kelebek1** [comment]
Where abouts exactly? Can you show a screenshot or video or something for where? Is it in the cave the save you posted is? I picked up the 3 minerals and went outside and it was fine for me, no crash.

**Comment by DreadwyrmBahamut** [comment]
On steamdeck?, and literally right when you enter pentelas region on vulkan on 2888 on steam deck, it freezes, screen goes black, then comes back up and freezes indefinitely, it doesnt happen right away sometimes i was able to stay in there the first time for about 2-5 minutes before it started happening, now i cant even make it 1 step

**Comment by DreadwyrmBahamut** [comment]
Confirmed its still happening in 2889 as well, and for my friend too.

https://ibb.co/wcmY1KW

**Comment by DreadwyrmBahamut** [comment]
Confirmed still happening in 2890

**Comment by DreadwyrmBahamut** [comment]
Has anyone been able to replicate the issues we're having or what?

**Comment by CaptainDerank** [comment]
It sounds like the same problem i have. I currently can't progress when i am using Vulkan. When i enter the cutscene right in front of my save game the video first starts to play completely fine, but after changing into the second cutscene, first yuzu freezes then my displays get black and turn back on and then my complete Wayland Session freezes.
The cutscene plays "fine" (Graphical glitches) when i am using OpenGL.
The video is taken with a ResMod, but the logs are from a try with clean Vulkan Shaders and no ResMod.

Video (too big for Github...): https://www.youtube.com/watch?v=HabSPdD_en0
Savegame: [xc3_save.zip](https://github.com/yuzu-emu/yuzu/files/9275940/xc3_save.zip)
Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9275941/yuzu_log.txt)
System:
```
System:
  Host: user-linux Kernel: 5.18.16-zen1-1-zen-vive arch: x86_64 bits: 64
    compiler: gcc v: 12.1.1 Desktop: KDE Plasma v: 5.25.3 Distro: Arch Linux
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX X570-E GAMING v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 4021
    date: 08/09/2021
Battery:
  Device-1: ps-controller-battery-xx:xx:xx:xx:xx:xx model: N/A charge: N/A
    status: discharging
CPU:
  Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP arch: Zen 3
    rev: 0 cache: L1: 1024 KiB L2: 8 MiB L3: 64 MiB
  Speed (MHz): avg: 4173 high: 4445 min/max: 2200/5083 boost: enabled
    cores: 1: 4241 2: 3459 3: 3714 4: 3573 5: 4416 6: 4342 7: 3488 8: 4333
    9: 4257 10: 4372 11: 4358 12: 4242 13: 4293 14: 4192 15: 4015 16: 4105
    17: 4142 18: 4316 19: 4151 20: 4344 21: 4281 22: 4342 23: 4217 24: 4371
    25: 4253 26: 4087 27: 4416 28: 4359 29: 4347 30: 3816 31: 4277 32: 4445
    bogomips: 217194
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] vendor: ASUSTeK
    driver: amdgpu v: kernel arch: RDNA 2 bus-ID: 0d:00.0
  Device-2: NVIDIA GA104 [GeForce RTX 3070] vendor: CardExpert
    driver: vfio-pci v: N/A arch: Ampere bus-ID: 0e:00.0
  Device-3: Logitech StreamCam type: USB
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus-ID: 2-2:2
  Display: wayland server: X.Org v: 22.1.3 with: Xwayland v: 22.1.3
    compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 3440x1440~144Hz
  OpenGL: renderer: AMD Radeon RX 6900 XT (sienna_cichlid LLVM 14.0.6 DRM
    3.46 5.18.16-zen1-1-zen-vive)
    v: 4.6 Mesa 22.1.4 direct render: Yes
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus-ID: 05:00.0
  IF: wlp5s0 state: down mac: xx:xx:xx:xx:xx:xx
  Device-2: Realtek RTL8125 2.5GbE vendor: ASUSTeK driver: r8169 v: kernel
    port: d000 bus-ID: 06:00.0
  IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: xx:xx:xx:xx:xx:xx
  Device-3: Intel I211 Gigabit Network vendor: ASUSTeK driver: igb
    v: kernel port: c000 bus-ID: 07:00.0
  IF: enp7s0 state: down mac: xx:xx:xx:xx:xx:xx
  IF-ID-2: team0 state: down mac: xx:xx:xx:xx:xx:xx
Drives:
  Local Storage: total: 8.41 TiB used: 4.72 TiB (56.2%)
Info:
  Processes: 509 Uptime: 33m Memory: 62.71 GiB used: 8.97 GiB (14.3%)
  Init: systemd Compilers: gcc: 12.1.0 clang: 14.0.6 Packages: 2458
  Shell: Zsh v: 5.9 inxi: 3.3.19
```

**Comment by DreadwyrmBahamut** [comment]
> It sounds like the same problem i have. I currently can't progress when i am using Vulkan. When i enter the cutscene right in front of my save game the video first starts to play completely fine, but after changing into the second cutscene, first yuzu freezes then my displays get black and turn back on and then my complete Wayland Session freezes. The cutscene plays "fine" (Graphical glitches) when i am using OpenGL. I also tried to replicate the problem with Windows, but when i am using Vulkan on my NVIDIA RTX 3070, the cutscenes play fine. The video is taken with a ResMod, but the logs are from a try with clean Vulkan Shaders and no ResMod.
> 
> Yuzu Version: EA 2890 Video (too big for Github...): https://www.youtube.com/watch?v=HabSPdD_en0 Savegame: [xc3_save.zip](https://github.com/yuzu-emu/yuzu/files/9275940/xc3_save.zip) Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9275941/yuzu_log.txt) System:
> 
> ```
> System:
>   Host: user-linux Kernel: 5.18.16-zen1-1-zen-vive arch: x86_64 bits: 64
>     compiler: gcc v: 12.1.1 Desktop: KDE Plasma v: 5.25.3 Distro: Arch Linux
> Machine:
>   Type: Desktop Mobo: ASUSTeK model: ROG STRIX X570-E GAMING v: Rev X.0x
>     serial: <superuser required> UEFI: American Megatrends v: 4021
>     date: 08/09/2021
> Battery:
>   Device-1: ps-controller-battery-xx:xx:xx:xx:xx:xx model: N/A charge: N/A
>     status: discharging
> CPU:
>   Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP arch: Zen 3
>     rev: 0 cache: L1: 1024 KiB L2: 8 MiB L3: 64 MiB
>   Speed (MHz): avg: 4173 high: 4445 min/max: 2200/5083 boost: enabled
>     cores: 1: 4241 2: 3459 3: 3714 4: 3573 5: 4416 6: 4342 7: 3488 8: 4333
>     9: 4257 10: 4372 11: 4358 12: 4242 13: 4293 14: 4192 15: 4015 16: 4105
>     17: 4142 18: 4316 19: 4151 20: 4344 21: 4281 22: 4342 23: 4217 24: 4371
>     25: 4253 26: 4087 27: 4416 28: 4359 29: 4347 30: 3816 31: 4277 32: 4445
>     bogomips: 217194
>   Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
> Graphics:
>   Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] vendor: ASUSTeK
>     driver: amdgpu v: kernel arch: RDNA 2 bus-ID: 0d:00.0
>   Device-2: NVIDIA GA104 [GeForce RTX 3070] vendor: CardExpert
>     driver: vfio-pci v: N/A arch: Ampere bus-ID: 0e:00.0
>   Device-3: Logitech StreamCam type: USB
>     driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus-ID: 2-2:2
>   Display: wayland server: X.Org v: 22.1.3 with: Xwayland v: 22.1.3
>     compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
>     gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 3440x1440~144Hz
>   OpenGL: renderer: AMD Radeon RX 6900 XT (sienna_cichlid LLVM 14.0.6 DRM
>     3.46 5.18.16-zen1-1-zen-vive)
>     v: 4.6 Mesa 22.1.4 direct render: Yes
> Network:
>   Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus-ID: 05:00.0
>   IF: wlp5s0 state: down mac: xx:xx:xx:xx:xx:xx
>   Device-2: Realtek RTL8125 2.5GbE vendor: ASUSTeK driver: r8169 v: kernel
>     port: d000 bus-ID: 06:00.0
>   IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: xx:xx:xx:xx:xx:xx
>   Device-3: Intel I211 Gigabit Network vendor: ASUSTeK driver: igb
>     v: kernel port: c000 bus-ID: 07:00.0
>   IF: enp7s0 state: down mac: xx:xx:xx:xx:xx:xx
>   IF-ID-2: team0 state: down mac: xx:xx:xx:xx:xx:xx
> Drives:
>   Local Storage: total: 8.41 TiB used: 4.72 TiB (56.2%)
> Info:
>   Processes: 509 Uptime: 33m Memory: 62.71 GiB used: 8.97 GiB (14.3%)
>   Init: systemd Compilers: gcc: 12.1.0 clang: 14.0.6 Packages: 2458
>   Shell: Zsh v: 5.9 inxi: 3.3.19
> ```

This is heroic, thanks for sharing. The more people sharing the better and quicker it will get fixed (hopefully)

**Comment by CaptainDerank** [comment]
A little Update from my side: I just tried it with X11 and with the new EA 2891 and on X11 it also freezes the whole session, so it's not only a wayland thing.

**Comment by CaptainDerank** [comment]
Ok another Update: I quickly booted up a EndeavourOS VM with my NVIDIA RTX 3070 and there the freeze does not occur. So it seems to be a AMD only problem.

**Comment by DreadwyrmBahamut** [comment]
> A little Update from my side: I just tried it with X11 and with the new EA 2891 and on X11 it also freezes the whole session, so it's not only a wayland thing.

Damn it I got excited when I seen the new release then checked here and my hopes were dashed again lol

**Comment by DreadwyrmBahamut** [comment]
This is crazy, 2895 and its still having the same issue, 7 versions later. Is this really such a hard issue to fix? Does anyone even know the true cause yet?

**Comment by CaptainDerank** [comment]
I tried to get some coredumps so the devs can see where the crash happens, but sadly the coredumps doesn't contain any helpful information or none gets created.
I just played the crashing part with OpenGL (even when it have some vertex glitches for me...) and then switched back to Vulkan.

**Comment by CaptainDerank** [comment]
So i collected every information that i can collect.
I got the crash information from dmesg, a coredump of the maintenance tool and from yuzu

[dmesg.log](https://github.com/yuzu-emu/yuzu/files/9284137/dmesg.log)
[maintenancetool_backtrace.log](https://github.com/yuzu-emu/yuzu/files/9284138/maintenancetool_backtrace.log)
[yuzu_ea_backtrace.log](https://github.com/yuzu-emu/yuzu/files/9284139/yuzu_ea_backtrace.log)
.

**Comment by DreadwyrmBahamut** [comment]
> So i collected every information that i can collect. I got the crash information from dmesg, a coredump of the maintenance tool and from yuzu.
> 
> I can't run a self compiled Debug Build of yuzu so the symbols unfortunately doesnt get resolved.
> 
> [dmesg.log](https://github.com/yuzu-emu/yuzu/files/9284137/dmesg.log) [maintenancetool_backtrace.log](https://github.com/yuzu-emu/yuzu/files/9284138/maintenancetool_backtrace.log) [yuzu_ea_backtrace.log](https://github.com/yuzu-emu/yuzu/files/9284139/yuzu_ea_backtrace.log)

Anything is appreciated, honestly, very appreciated, anything to help the devs fix it. It's crazy how much this game has wrong with it no wonder it runs like shit on the switch too

**Comment by CaptainDerank** [comment]
> So i collected every information that i can collect. I got the crash information from dmesg, a coredump of the maintenance tool and from yuzu.
> 
> I can't run a self compiled Debug Build of yuzu so the symbols unfortunately doesnt get resolved.
> 
> [dmesg.log](https://github.com/yuzu-emu/yuzu/files/9284137/dmesg.log) [maintenancetool_backtrace.log](https://github.com/yuzu-emu/yuzu/files/9284138/maintenancetool_backtrace.log) [yuzu_ea_backtrace.log](https://github.com/yuzu-emu/yuzu/files/9284139/yuzu_ea_backtrace.log)

Ah shit like i thought, even with resolved yuzu symbols, it doesn't really contain usable info...
```
#0  0x00007f893aaa04dc in  () at /usr/lib/libc.so.6
#1  0x00007f893aa50998 in raise () at /usr/lib/libc.so.6
#2  0x00007f893aa3a53d in abort () at /usr/lib/libc.so.6
#3  0x00007f893ac99833 in __gnu_cxx::__verbose_terminate_handler() () at /usr/src/debug/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007f893aca5cfc in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007f893aca5d69 in std::terminate() () at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007f893aca5fcd in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x564318bd1dc8 <typeinfo for Vulkan::vk::Exception>, dest=0x564317c5baa0 <Vulkan::vk::Exception::~Exception()>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00005643176d2fa8 in Vulkan::vk::Check(VkResult) (result=VK_ERROR_DEVICE_LOST) at /home/user/yuzu_ea/src/src/yuzu-linux-20220808-2946d90966-source/src/./video_core/vulkan_common/vulkan_wrapper.h:141
#8  0x00005643176d2fb6 in Vulkan::vk::Check(VkResult) (result=<optimized out>) at /home/user/yuzu_ea/src/src/yuzu-linux-20220808-2946d90966-source/src/./video_core/renderer_vulkan/vk_scheduler.h:132
#9  operator() (cmdbuf=..., __closure=0x7f04f3b6c688) at /home/user/yuzu_ea/src/src/yuzu-linux-20220808-2946d90966-source/src/video_core/renderer_vulkan/vk_scheduler.cpp:221
#10 Vulkan::Scheduler::TypedCommand<Vulkan::Scheduler::SubmitExecution(VkSemaphore, VkSemaphore)::<lambda(Vulkan::vk::CommandBuffer)> >::Execute(Vulkan::vk::CommandBuffer) const (this=0x7f04f3b6c678, cmdbuf=...) at /home/user/yuzu_ea/src/src/yuzu-linux-20220808-2946d90966-source/src/./video_core/renderer_vulkan/vk_scheduler.h:131
#11 0x0000564317ca6446 in Vulkan::Scheduler::CommandChunk::ExecuteAll(Vulkan::vk::CommandBuffer) (this=this@entry=0x7f04f3b6c600, cmdbuf=...) at /home/user/yuzu_ea/src/src/yuzu-linux-20220808-2946d90966-source/src/video_core/renderer_vulkan/vk_scheduler.cpp:28
#12 0x0000564317ca75e6 in Vulkan::Scheduler::WorkerThread(std::stop_token) (this=0x7f067d676d88, stop_token=...) at /home/user/yuzu_ea/src/src/yuzu-linux-20220808-2946d90966-source/src/video_core/renderer_vulkan/vk_scheduler.cpp:155
#13 0x0000564317ca7bdb in operator() (__closure=<optimized out>, token=...) at /home/user/yuzu_ea/src/src/yuzu-linux-20220808-2946d90966-source/src/video_core/renderer_vulkan/vk_scheduler.cpp:44
#14 std::__invoke_impl<void, Vulkan::Scheduler::Scheduler(const Vulkan::Device&, Vulkan::StateTracker&)::<lambda(std::stop_token)>, std::stop_token> (__f=<optimized out>) at /usr/include/c++/12.1.1/bits/invoke.h:61
#15 std::__invoke<Vulkan::Scheduler::Scheduler(const Vulkan::Device&, Vulkan::StateTracker&)::<lambda(std::stop_token)>, std::stop_token> (__fn=<optimized out>) at /usr/include/c++/12.1.1/bits/invoke.h:96
#16 std::thread::_Invoker<std::tuple<Vulkan::Scheduler::Scheduler(const Vulkan::Device&, Vulkan::StateTracker&)::<lambda(std::stop_token)>, std::stop_token> >::_M_invoke<0, 1> (this=<optimized out>) at /usr/include/c++/12.1.1/bits/std_thread.h:252
#17 std::thread::_Invoker<std::tuple<Vulkan::Scheduler::Scheduler(const Vulkan::Device&, Vulkan::StateTracker&)::<lambda(std::stop_token)>, std::stop_token> >::operator() (this=<optimized out>) at /usr/include/c++/12.1.1/bits/std_thread.h:259
#18 std::thread::_State_impl<std::thread::_Invoker<std::tuple<Vulkan::Scheduler::Scheduler(const Vulkan::Device&, Vulkan::StateTracker&)::<lambda(std::stop_token)>, std::stop_token> > >::_M_run(void) (this=<optimized out>) at /usr/include/c++/12.1.1/bits/std_thread.h:210
#19 0x00007f893acd62f3 in std::execute_native_thread_routine(void*) (__p=0x564319da2e30) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#20 0x00007f893aa9e78d in  () at /usr/lib/libc.so.6
#21 0x00007f893ab1f8e4 in clone () at /usr/lib/libc.so.6
```

I also could say that the device is gone :D I mean the radeon driver is crashing, of course the device is gone :D

**Comment by DreadwyrmBahamut** [comment]
Anyone test with newest version

**Comment by DreadwyrmBahamut** [comment]
Whatever I give up lol, just going to play on PC openGL

**Comment by jrobeson** [comment]
this is definitely still happening in the latest yuzu mainline builds, but I don't think it's a yuzu only problem. On Linux I was able to reproduce similar behavior with ryujinx and vulkan.  I think the problem is either with the kernel or mesa.

**Comment by wojiushixiaobai** [comment]
I have the same problem.
